---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: file-serve-pod
  name: file-serve
spec:
  containers:
  - image: registry.adathor.com/devops/file-serve:latest
    name: file-serve
    ports:
    - containerPort: 8080
      hostIP: 17.10.0.1
      hostPort: 12000
    volumeMounts:
    - mountPath: /app
      name: files_share-pvc
  volumes:
  - name: files_share-pvc
    persistentVolumeClaim:
      claimName: files_share
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: files_share
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

