apiVersion: ENC[AES256_GCM,data:ck0=,iv:FgCzV8i1sJ9+CGrBI7blodxGgI5LC65sveOR+rfxHTw=,tag:BleNDD8QASFbz7TR06RZkg==,type:str]
kind: ENC[AES256_GCM,data:Edow,iv:s5E7ZHTR0N9OoDEcgdR8m709WNAXtPaGU7yskWdoTRA=,tag:m8upT0MLovlNxomerPguNA==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:F9EGe6Nj+eaX1jdK4LI=,iv:w056OinLbCmzcUgI7EYOlJlZYmmhSLlYEZZxEUFYvlc=,tag:0y/j1hoeJ94ANypK9jZwDQ==,type:str]
    name: ENC[AES256_GCM,data:zQK9tQqzfCze6g==,iv:By0ZTqOEcYAjHPY/COTJXmiBSiDLbgiZ+CINNykVG2o=,tag:XXmZO92sK3dbmsFpFP+Q7A==,type:str]
spec:
    containers:
        - image: ENC[AES256_GCM,data:CMps9xuO4Sk1JcAtb3/ftcve0Xe6m4QQnDcDb7tySclwEyJubxNQt48ndTdK,iv:yhpi4nEXX8TPQ5gg9RSS8G+3knSsNTbJ1lGAC5aJz5s=,tag:rSbQ0/Sd4PA/521nWaRHeA==,type:str]
          name: ENC[AES256_GCM,data:24nmNbBPjXamZQ==,iv:tcNxiWL0yy+X6y7tpkSAD/J4qOTu9+VJQ2FXy1TtNQk=,tag:6IIHK7uq80miX2S8z0GukQ==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:/iNr1A==,iv:6sEBj/yd3pf08CNkVnSdqybHbTfpewrI9ZLtBH0jVU0=,tag:O9/2/xpK+mJCr3kg0OSaYw==,type:int]
              hostIP: ENC[AES256_GCM,data:aXDMj6ObuloT,iv:P3DnXv2oVbn3XRnhg4h31ErJ3aZ8Slt1yje6MB+aT3k=,tag:aOYKq0pNunuyleO3siVnYQ==,type:str]
              hostPort: ENC[AES256_GCM,data:Yfle040=,iv:izqAtbbUVM36TaKvac3/+HwVKiuPpDDK38jxAlg0beU=,tag:0Fd4+914vTLJUhssiGvV8A==,type:int]
          volumeMounts:
            - mountPath: ENC[AES256_GCM,data:ZHzTzw==,iv:X69IsNpOD5K2lPoOY1DsA8I7gpppkiBuyMBz06Wwdyk=,tag:Lr0MlLMwkEs1VLhvc+fpwQ==,type:str]
              name: ENC[AES256_GCM,data:1tMH2+rBmfLLY8k/xeXp,iv:AwpTZLTN1M2+F8GXY8Av6vC0Koiy6SGOJBGIr4n3srg=,tag:6l/Ug3IHlEMUUj/95MCjjA==,type:str]
    volumes:
        - name: ENC[AES256_GCM,data:ySOhc62YB1Sn6JBj+aU4,iv:BGx6HPSXrSRim/PybRcvtLatzooLaYEsDSQPpY67Cv0=,tag:kcWBLHcKX8XuxSCCAsGGgQ==,type:str]
          persistentVolumeClaim:
            claimName: ENC[AES256_GCM,data:rwYea4SPaoCJi0Y=,iv:XrmFg0xc0x3aYG485+w51RyPN6mrkppvmkAkn79lZGs=,tag:yXNG7Dd4pa/c9+Ee32WUHQ==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRXRreUFVV2tsWi85K1Nq
            aEhGbld4RFArTmgzYmZjRWxSdVB5dVVUckVrCjB3Z3BFbnFLamZzWmtkM1hYWU9P
            SzZoYnNxazVNN3o3bDBhcnpEQVF2a0kKLS0tIDEvR1VPNUlESERJdWJBY3BRemdq
            a2toSUFpQytGWm1FK1NzT0RLUXVKSGcKZrxXFPdYpD6bb5UwgDFCuY1OdfoE3Js6
            iS8dYR72XcjueD2yTwiLkKJNnHVbaya6mKYyng28XxtTWzGOV3UlRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:moTRKHbUFuk75rQ3sATGbwNVB6FlDU29W3UQ0x8J8IhkhOfEpFgaIrT7IFgBOjoYHJjquahUDZOdKF1XzH65JvUh39jJCs75nfXu1Vq5dGcaXhW+CgoD/tCTHUxweDCCE7gOZPstmFBkHNXEfBQ3VPO2VsJNneuYuIfG33lRlXE=,iv:yd1dgIqb705NMFisoyOdTXipNGqfo/YW4weAavUESTA=,tag:NWYBXg1xGVHRrCCQUVd/AA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:8yI=,iv:+oj9plmAdQY1BRqJ4FUHV9SX8coJjJuIZMpoEtHR/pA=,tag:TCvn5sUnEpJSauHuXLEQLw==,type:str]
kind: ENC[AES256_GCM,data:PRWVwTpRXvb/QCUZxg+ftPsp0jhP,iv:nVDQlHYb8dpm//QaAKGZXy135vIsDtn/a5OpPZSzzHg=,tag:2bzY26CHS8aMDyByhqteLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V0LxBBeIihB6Nio=,iv:em5IoE1QPmFZ+vs8Tsa8OWWwl2qOSZsq4ayPp5Q2Klw=,tag:iyZARaX5eLUFwVMSC9dAcA==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:9pChdbHidaOc0yXejw==,iv:erzD4ymQf3OY/LkawyyzxP52arVWN26ZEu2+7MQfiZ4=,tag:69B9/QaBc95EwbkV76knWQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:tJEaOg==,iv:rLw3vNdW3zFCtAR4pQlUrwzxfElAHs6e93KtE3q0Ui4=,tag:RnOVaEwlmesmO4jHTB7YUg==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRXRreUFVV2tsWi85K1Nq
            aEhGbld4RFArTmgzYmZjRWxSdVB5dVVUckVrCjB3Z3BFbnFLamZzWmtkM1hYWU9P
            SzZoYnNxazVNN3o3bDBhcnpEQVF2a0kKLS0tIDEvR1VPNUlESERJdWJBY3BRemdq
            a2toSUFpQytGWm1FK1NzT0RLUXVKSGcKZrxXFPdYpD6bb5UwgDFCuY1OdfoE3Js6
            iS8dYR72XcjueD2yTwiLkKJNnHVbaya6mKYyng28XxtTWzGOV3UlRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:moTRKHbUFuk75rQ3sATGbwNVB6FlDU29W3UQ0x8J8IhkhOfEpFgaIrT7IFgBOjoYHJjquahUDZOdKF1XzH65JvUh39jJCs75nfXu1Vq5dGcaXhW+CgoD/tCTHUxweDCCE7gOZPstmFBkHNXEfBQ3VPO2VsJNneuYuIfG33lRlXE=,iv:yd1dgIqb705NMFisoyOdTXipNGqfo/YW4weAavUESTA=,tag:NWYBXg1xGVHRrCCQUVd/AA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
