apiVersion: ENC[AES256_GCM,data:j7s=,iv:g20xSxdajw/y13PXKbSRs8IVxNQDhRGvi3pVWqGGA9A=,tag:FN5rIlC6KBcQBxh/Gt8D5g==,type:str]
kind: ENC[AES256_GCM,data:SP8uH7lyb3uV,iv:o86pQ0vPUCtWjBchQP7aEjSHQT6/yji8LJE/fC2pswQ=,tag:JRKI506k1ikNmNuihuw+DQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UwMobiF4U85r/cp9wf/e49jUBQ==,iv:rymZCEljY/8kDiSOh1Yaj8tt3qxpL8ZY+hMuS8TE7dQ=,tag:R9fibz/1/o/hkhpsD6YqlQ==,type:str]
data:
    inventory.ini: ENC[AES256_GCM,data:YyK3Mws51sE3gSDw/J4SEWYb1q9iIukt2WIH4KlJjS7mx/aXyfnCQcbRsqxjfP+EiUt54R0GlaO0s1ms4mDPvNB3ju2OwIgLg01dv/uawqnEUnM5PLz1P93YKDMpk/nd2CNYNy8f9nQfTpCc1zj4yCpV6877FFtylc6n7dLTJ6urgDJ4hbPuYULAkBVHui3ib1U8QTbanxm85tCsodO/XyD+IH6vl7Z5kmDa3fVKeCNsCjHKzN3UqOQ+BPkqjR8KXcuPaVeuOPQitWphMvE3PWf6Fmsa7BBD319p6QoCSA==,iv:SpkEiOfWFATpQjELgY7FbfmQnCQQ0DVNmv4STdUPbIY=,tag:DlY2sRYiQG9QxTv57LnegA==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTWVaaXAxdUtzWVBvKzRI
            U1lOY3ZDZXV1eUhaRnV3U0Nsbmh6QWgwTzJBCmY1THZWTXBOSGJCMW40Vm5ybU9J
            S2s2NWFIYmZxYzFrLzZSTDRhSFNaK2cKLS0tIDVMc1BQc1RmMHRlYzdGR0JsaEZE
            Sm11QldQV04vWHdhMytwVTBoTGc1ancKFZp6vhqDJu48S3DbDqgTPLjcCmAmlE5d
            PrXiy+6rZh9goyMxriUjYP4TiWVmR9DefH0rT7qMvgvgHXzPu2g5gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:5dWUOe6M71Thbx4rOMu0ZEkcHt2YmguAByy10y83Eh6h2qPS5wadkZzqA38/mPtZWbASpBxH1Td/XTAW+LQ5HO8m44G9NI+XtHZuODZ0nwTp0mJbwgsAjkKeqhTMFQS4yirIbZ89EEX1j0rwTkOPV0qDRt1w+GYsvCcgZjswaa8=,iv:TiOdN0u3IiFAvHtLxSDegUBvseHtNQr1L1Lq8AGnwnE=,tag:91JgThQ/uzE5zFkz2H7cYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
