apiVersion: v1
kind: Pod
metadata:
  labels:
    app: homepage-pod
  name: homepage-pod
spec:
  containers:
  - name: homepage
    image: registry.adathor.com/devops/homepage:latest
    ports:
    - containerPort: 3000
      hostPort: 4000
