apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-02T04:09:19Z"
  labels:
    app: homepage-pod
  name: homepage-pod
spec:
  containers:
  - args:
    - node
    - server.js
    image: registry.adathor.com/devops/homepage:latest
    name: homepage
    ports:
    - containerPort: 3000
      hostPort: 4000
