apiVersion: ENC[AES256_GCM,data:8fc=,iv:9dY55RYO/OiQeJNa/s27Wj0FXbnfDi4WEYkUZwruM+c=,tag:pHM+zW793sZl2slH7xSotw==,type:str]
kind: ENC[AES256_GCM,data:/hsx,iv:DM8i5iWHhKMsonpFgoJ4QNxBHdGv8TFPibuOZZI6Tac=,tag:5L2Xhai6bdUI3nTOuuRCOQ==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:UIHoBhBO/SiezW5y,iv:+z0TLdlzkZMI+LLuxOU29FU9+ztohchuaQvamQCMA/U=,tag:GYJ6Ma81crsLhIjyagHzGg==,type:str]
    name: ENC[AES256_GCM,data:O334YXAmAumqreC8,iv:6fZU1caL2ZTDl7Z09Ojou1N59j+umFeqgw2QJiMWW5I=,tag:vnav0rQpF1dkaOrwvNcaJQ==,type:str]
spec:
    containers:
        - name: ENC[AES256_GCM,data:P1G+JD5VxuY=,iv:QKebk65roNunR/DIPMw9d/HWdS9q+AyLkhBUjDgx68U=,tag:LGnXvSPn8vBjEsDTZCMDTg==,type:str]
          image: ENC[AES256_GCM,data:gQZYkYfyeW5+FUBif1Hf2I5KzIe5Mko//1DI+60f8ODegf7dM+oDXtsVSA==,iv:C/0Hy+OvcXPCVqovBkFs29R3COfyg9pfMr31OgFHtVg=,tag:0fP250JhXNe+5ZAjyBwZww==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:y0E0IQ==,iv:5npEIVUDtibOUTy7azId5pxJ6GOBvY/ogmrTdUpuwRM=,tag:cGRlwUeZsLQhkC2b+EG+zA==,type:int]
              hostPort: ENC[AES256_GCM,data:B6y8uQ==,iv:P9LBnXIEqblfAPvLohV4eskcVgYu3KTK/4XNiUjDrDQ=,tag:LydcttqPzDDl2/JjnqFfsg==,type:int]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWmRHbklEOSt0cjhwYWhw
            Z3dydmloSXV2TVpJM1AzRk9uSGxUbFE5M2hvCjNkUndOcUNoeCt5S2MvUE45cHdB
            REhDMEJLTVBKYTRzZFhzYkhwUnFLYTAKLS0tIHV1bnlZTEozb3FNMzlDSXQ4UUdH
            dmx4cy9FcDJOV1VLaklEckRqWTZLYVUKdoThCDvt2vwB9xVBBJ/cnyTtV2FA4aT6
            uTHSNaYW387F7i/q6mWdPsp+EItj8MzfLmZLYFb+U7KSX9aIx4yjgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:ve/BANbpphsh5vZE8e1ouMAE6lTGN8GfFyeUTevpJEkpG70s6jfSStHHT0/NT2s8sciH/dBRb1Wx56tpwJkD7DnnLemB0RazKpQoXTIU1fZH5bgQyICkhHSupAr8eOWQh4vCMCTyimadY53uJ0DeMV1dGT5A6sdzzKkaiHmbOTU=,iv:zk1mC21rW70O0RaX32dpfFbs52Sgs5FFA3ZZmCFORdk=,tag:hkQuy2/v7RD+fLTxjnrTOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
