apiVersion: ENC[AES256_GCM,data:7xQ=,iv:y3SVxNkYnCwzY0nHRJDRdB0b42gOX7QiiuXjXAiRDcY=,tag:JJ1N4oSLfdIcu0DaB/Jr1w==,type:str]
kind: ENC[AES256_GCM,data:73WN,iv:pHAWHFE6pDMTuVq6i4395mE9tn4CEzF1GKBEd7qHFwA=,tag:8crg5GfJYYKdTqoxW8MOFA==,type:str]
metadata:
    annotations:
        io.containers.autoupdate: ENC[AES256_GCM,data:1h1NRGrCSeE=,iv:O9I8RyFhyqFP/bjmiq+oY+gIk/QnqP/7OgzI790OGQY=,tag:E3GNP1tglM2VlJn0GQxpCA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:aJxmvd4WbbGJ+6hR,iv:h7NRq9sJpt1hPP0shy+Xh7issMfxsOx9mqWmaxQYZGo=,tag:PEy6xILHbmlu85Gd/BszNw==,type:str]
    name: ENC[AES256_GCM,data:8sbadVN85xc6Tuf0,iv:cD6VgMvjeLHxbJwCSc8+9d26uqGJ9oSmK+zP+jzZVf8=,tag:WyxQfnOd3nP579YWhdahyQ==,type:str]
spec:
    containers:
        - image: ENC[AES256_GCM,data:21h8TLwShoCdVMpV1DEzHTQOn+UdE43CmCj2Wai7BseumsttGg==,iv:LcGLckVJm8C45jBRrvmmM9Y9O6gX6sE0lO9fJtYt5yk=,tag:TeclFwVsxSY0q21pWWnKSg==,type:str]
          name: ENC[AES256_GCM,data:Utkd+UnF62g=,iv:3JBGz18m6UjGoWqZaO/0A7OPyErJ96K2H0ZwlwhPzd0=,tag:0pR7Gf2rH8Bg1aBO63P64g==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:ZHJBcw==,iv:9GOv++oMOlXWP0s764PlE/ygs7KO3cs8LpufS1owOyM=,tag:6ddCQ0be2r6L/ampUaR3pQ==,type:int]
              hostPort: ENC[AES256_GCM,data:L/Lo5g==,iv:W7kf6rQ76D/pyfkicnslVjyO4JQUNV3kwcxLkyePSqE=,tag:sdCdKwb8MMISzt7MF/HZuw==,type:int]
          volumeMounts:
            - mountPath: ENC[AES256_GCM,data:5q1GFPQ=,iv:qPM97NT1pJiCrq/AU42e59JEiH63wPm7JdWanOHVffs=,tag:OF71wbpWYMPrX+NCHdG4AA==,type:str]
              name: ENC[AES256_GCM,data:5iecX9W6ORFVSZGtVwG3dQ==,iv:Kn70/1BGOJdkW8DYEIOZ4tE2aBEjeUDDRreKMEXMZn0=,tag:yfm+JYpqhwktRmOhLMuNKw==,type:str]
    volumes:
        - name: ENC[AES256_GCM,data:4s0UnImHHOhF261BJ4vRxw==,iv:MehAkf4qSHx5JUK5QFT+Pfh2I6695yTTjXC+VSLOpTE=,tag:3hvjS1HUW64D3G20fs3VTg==,type:str]
          persistentVolumeClaim:
            claimName: ENC[AES256_GCM,data:kKHL56x0TEuE/COK,iv:dX2qbwK+2Eg6sXzDZf8zrgRtsOC1NKeWo54oav8s28I=,tag:8+CVXU1Ym3SS1x8Q7BCGcg==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaHVpa0NMNlU4RTFqZllK
            K0gxK1NKMnpscmZ5TlY0K0lKUHVDUTZ0RVVFClVZS255SmtUVTFSdEpPcWZ4Rll1
            Tkg5YXd4dWxqVi9WMHArMVJrQ1B2clkKLS0tIEsvYVd5NTlzc3VIcHljN2UwWjFC
            em83aHVjemhnRHpyaDBqWlR4allGS28Kr+TKHT93te2EWayMgRLHbiYUhzGHsCu7
            TPGKZ2Uo3NQoDS9kJN97m4KX9jeQwvbaBxzQJ0gCytqLzXXck8CwVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:1+CZeogIzsBLF5BfRsg/8R5B14mjnA2UK/cItfGo4qX9eoe7z5LSNdA6TKb2ubDkJGZqmtSNFeBgBWsGMPM58psAfqwuc8X2Vf4Rdo7CjYaaUQm6U4oGcyhXSborDAnZZgPY4z+Ymfl6zXRzC2TVldvKUIKsJ8j4Ke6JumMY0HU=,iv:bCm78edU2HvAAINkZaaD9gY5hQLphrzdg7YcYQ2Vc7U=,tag:Cw6mOF9gEVcTsKaxARMM8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:GRw=,iv:IQIxGfS+bfdRwL2GPSpgWQdF/KnPyMPl1bJj9aU7vjI=,tag:twnOU2HSl15oTcDAMGrsvg==,type:str]
kind: ENC[AES256_GCM,data:E+H2SEgk0kua57uedU6hSkU+30x3,iv:LqchdDi6IhEqD5FWhiqJqK4NsYBK3XP+8mTWrFukY2A=,tag:UxN/Pymx8jKqXYsUttGnbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Swbppjn3DtdFbGTn,iv:SGWsk1fmLwhRpBNPKd7ZaZxH/5/YcwfSdQDHPnPcGjI=,tag:ZP/NH9TmYIa9W/+PCzfqOQ==,type:str]
    labels:
        app: ENC[AES256_GCM,data:G8EED4k0qg6Qkc7/,iv:PIklUNcfysSE0rGtjrOQikem7iohYEyH0adhw1Nc1fo=,tag:7lRI2ZvSu3/HfixKp3MrsQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:1Sw6qKa4rk+/8yJlWg==,iv:CyPum1s2X8zKPsQh54ibiZDkiD9NaySWZbPowovci3w=,tag:Sn5hKq6YGBlR3tEamDF6UQ==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaHVpa0NMNlU4RTFqZllK
            K0gxK1NKMnpscmZ5TlY0K0lKUHVDUTZ0RVVFClVZS255SmtUVTFSdEpPcWZ4Rll1
            Tkg5YXd4dWxqVi9WMHArMVJrQ1B2clkKLS0tIEsvYVd5NTlzc3VIcHljN2UwWjFC
            em83aHVjemhnRHpyaDBqWlR4allGS28Kr+TKHT93te2EWayMgRLHbiYUhzGHsCu7
            TPGKZ2Uo3NQoDS9kJN97m4KX9jeQwvbaBxzQJ0gCytqLzXXck8CwVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:1+CZeogIzsBLF5BfRsg/8R5B14mjnA2UK/cItfGo4qX9eoe7z5LSNdA6TKb2ubDkJGZqmtSNFeBgBWsGMPM58psAfqwuc8X2Vf4Rdo7CjYaaUQm6U4oGcyhXSborDAnZZgPY4z+Ymfl6zXRzC2TVldvKUIKsJ8j4Ke6JumMY0HU=,iv:bCm78edU2HvAAINkZaaD9gY5hQLphrzdg7YcYQ2Vc7U=,tag:Cw6mOF9gEVcTsKaxARMM8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
