apiVersion: ENC[AES256_GCM,data:jXs=,iv:n66vWXyUouufVW6DC7C4OWx+z6nBWn7b6h6pRp0u+SE=,tag:brN3DOPYgx/uXAPR8Ta9BA==,type:str]
kind: ENC[AES256_GCM,data:ExlV,iv:VtQewKbBLLZEKWYs70CLslMLV6+QHNjdORMGOMvh8N0=,tag:azeLp2ZORCjvGrpMYmFmNA==,type:str]
metadata:
    annotations:
        io.containers.autoupdate: ENC[AES256_GCM,data:lwM0DlrHEn8=,iv:Nh11ZTciVH8WJxsB9FKPm4IlIu/P6qKjvsix2S+Jd5A=,tag:ypE7f2djY8aEZTt8zgZUNw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:r6at1GrxMzGNnQ==,iv:SLJ8ipbbB1mAJQI0yMtfwGL4E+xvfttIZE6ZksyOpIA=,tag:gnNVELFWYb01hsF60em0pw==,type:str]
    name: ENC[AES256_GCM,data:21YhtWfJoGjCdw==,iv:FViG1KXXwWMAA2qEw1WRidjNrgZQmj8Sd0v9yAxkZYM=,tag:85DKpTZ0DKFfLqnkyaaChQ==,type:str]
spec:
    containers:
        - name: ENC[AES256_GCM,data:CSplz16wOlC18Ac=,iv:WK8TwfjPtTAIFxfRI6ScPDdAW/KWcizCarfoBN//pOE=,tag:4677fbSKnVJy8Nqb8m5Mog==,type:str]
          image: ENC[AES256_GCM,data:PsjGBvYb3l+uqe/CV/29NcHF7sRUyQ1HKEFt4+I3GnQ=,iv:l5fHBZwDwlrFK5eRIr11Xg/LJe3yiuGDeKXEBH7zjGU=,tag:q8VeWNYJWw0vBh+UING7Fg==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:mxPQOA==,iv:gPlr/MqreQOdnf4dQwwG55NZDuheCaq6K43rAjsRQVk=,tag:v3in34zU71d+ho07lXXFWQ==,type:int]
              hostPort: ENC[AES256_GCM,data:LlJYbQ==,iv:fu4uOIR7IvcO8OF7GAwoXQ6jQnzxRRFAci+a5sxKfVI=,tag:j49N3J/PWg6M4vA3Aa0bDQ==,type:int]
          volumeMounts:
            - mountPath: ENC[AES256_GCM,data:zn7AAUrKCu7p,iv:nOZ4KNBs8ahh7DdaH7a8RLrO568Fr7AUlpV9ajLzmbo=,tag:QTP+KjoK+c7k+mXxo2IT2w==,type:str]
              name: ENC[AES256_GCM,data:oWofwWMI8UbdBw==,iv:VkDVxVOcCp0xuKdLjo/0qVtBvGZZo3/DlxbMfSKLZ9I=,tag:S57Ly37D8tvgp3PajMXkPQ==,type:str]
    volumes:
        - name: ENC[AES256_GCM,data:EjbdFZe/n3Hcbw==,iv:arisXhD92ISppqD3uqPcDrScuhoOq1Bnbd7cbR4jris=,tag:7Pd6RgM82TKhEAWuYOBLzg==,type:str]
          persistentVolumeClaim:
            claimName: ENC[AES256_GCM,data:ce3EIzTJ,iv:j/pwbTQU02P44hj6XFgwhNbb+ses4bcBXKCamg3ykDg=,tag:bQDO2SPgVAZ2stDvolBDgw==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZTlyRVREc1htd2t1Rzc3
            c2EwS1JQSjZsbEcvS1FONXkxZnY5SEZRRDB3ClcySlRrblFBb0VMcjM3RFFUeVdZ
            eUxVRzMvcjR6Um8vZExNQUdpN3g3Y0EKLS0tIERIa0FRallmZkFZWlZ3TTFwTnJC
            SURHdTNONkQ2SDlNZDMxbnIvaU1TYXMK5Bos8zkftdFFOVsISTvLaJ15++Q03ICD
            qJokX9a9dsR2FE76kLtpVzdvl0XAYx2Z+5WgbWiDJin9ys8YNAGRSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:QGBuj/uI2/59uf82Wsw4ZmuVqw9nfoaSM+HOcwEuuz+JMCJn1NRl2S+d5wkBJMlKJ9y4QMf+MriZxZfQcVGYZaYL9B1gp7nwwRK2KFy111LyNHewijB5HUe7tpg6WAio6poaybwJCETdHoh+qkTSnHE0CyHNHABWwXHCY4OVnFw=,iv:XCNenilL/gYXmoA/vT0sfT//J0llovrtR5SAhXMAEls=,tag:qbbAOek6dEz7/ZyysQV1fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:11Q=,iv:mRVuLC/CsYj9cmijhrFFB6KpQ6oNL8GhqfrsTUqyhDQ=,tag:yy1cY/O5xrR/m2VWGFCx1w==,type:str]
kind: ENC[AES256_GCM,data:d4mxw7awu/0KkmZBa1wOYUYR9pTf,iv:lDEgm6EdMJTCu7pIlW998aJgbnP2bnEzKWbZ9+uFiY8=,tag:IkSyh2RbuDy6lR4PUTSgyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qHlT+GHQ,iv:UXhiuMatOBQjMuZPzT6hwJPWnMuOZTQdBDhgSxe+TBQ=,tag:6xc2j/KeDQvVSqtKLHqlnw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:tNG/i7iawpr6CQ==,iv:Gd9iLRTPAYRGrgPBjwcEglDavJr+ke68ZoalADbNjYM=,tag:+auSG5M3D1uBjmhRAEhxQw==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:tY/vhqzXjwqK08t+IA==,iv:F4DrhGSv8ELYXEmkTXObjcc6J85Wp0jGjkQPC7RLlZ4=,tag:lW4rlVGLaToNO74rB3O7rg==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZTlyRVREc1htd2t1Rzc3
            c2EwS1JQSjZsbEcvS1FONXkxZnY5SEZRRDB3ClcySlRrblFBb0VMcjM3RFFUeVdZ
            eUxVRzMvcjR6Um8vZExNQUdpN3g3Y0EKLS0tIERIa0FRallmZkFZWlZ3TTFwTnJC
            SURHdTNONkQ2SDlNZDMxbnIvaU1TYXMK5Bos8zkftdFFOVsISTvLaJ15++Q03ICD
            qJokX9a9dsR2FE76kLtpVzdvl0XAYx2Z+5WgbWiDJin9ys8YNAGRSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T01:00:26Z"
    mac: ENC[AES256_GCM,data:QGBuj/uI2/59uf82Wsw4ZmuVqw9nfoaSM+HOcwEuuz+JMCJn1NRl2S+d5wkBJMlKJ9y4QMf+MriZxZfQcVGYZaYL9B1gp7nwwRK2KFy111LyNHewijB5HUe7tpg6WAio6poaybwJCETdHoh+qkTSnHE0CyHNHABWwXHCY4OVnFw=,iv:XCNenilL/gYXmoA/vT0sfT//J0llovrtR5SAhXMAEls=,tag:qbbAOek6dEz7/ZyysQV1fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
