http:
  services:
    ittools:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:8082"
    crate:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:8888"
    uptime:
      loadbalancer:
        servers:
        - url: "http://17.10.0.1:3001"
    home:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:4000"
    hole:
      loadbalancer:
        servers:
        - url: "http://17.10.0.1:8082"
    grafana:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:3030"
    ara-api:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:8085"
    hedgedoc:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:3010"
    parallel:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:8008"
    harbor-reg:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:9181"
    gitea:
      loadbalancer:
        servers:
        - url: "http://17.10.0.20:3001"

  routers:
    crate:
      rule: "Host(`crate.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: crate
      entryPoints:
        - "https"
      middlewares: crate-chain
    ittools:
      rule: "Host(`it-tools.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: ittools
      entryPoints:
        - "https"
    uptime:
      rule: "Host(`uptime.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: uptime
      entryPoints:
        - "https"
    home:
      rule: "Host(`home.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: home
      entryPoints:
        - "https"
    hole:
      rule: "Host(`hole.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: hole
      entryPoints:
        - "https"
    grafana:
      rule: "Host(`monitoring.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: grafana
      entryPoints:
        - "https"
    ara-api:
      rule: "Host(`ara.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: ara-api
      entryPoints:
        - "https"
      middlewares: authie
    hedgedoc:
      rule: "Host(`hedgedoc.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: hedgedoc
      entryPoints:
        - "https"
    parallel:
      rule: "Host(`matrix.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: parallel
      entryPoints:
        - "https"
    harbor-reg:
      rule: "Host(`registry.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: harbor-reg
      entryPoints:
        - "https"
    osc-old:
      rule: "Host(`openstorage.io`)"
      tls:
        certResolver: letsencrypt
      service: home
      entryPoints:
        - "https"
      middlewares:
      - xyz-redirect
    gitea:
      rule: "Host(`gitea.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: gitea
      entryPoints:
        - "https"
    bar:
      rule: "Host(`bar.adathor.com`)"
      tls:
        certResolver: letsencrypt
      service: home
      entryPoints:
        - "https"
      middlewares:
      - bar-redirect

  middlewares:
    crate-chain:
      chain:
        middlewares:
          - crate-headers
          - crate-redirect
          - crate-webfinger-nodeinfo-redirect
    crate-redirect:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"
    crate-webfinger-nodeinfo-redirect:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(webfinger|nodeinfo)"
        replacement: "https://${1}/index.php/.well-known/$$2"
    crate-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
    wg-only:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.222.0.0/24"
        ipStrategy:
          depth: 2
    bar-redirect:
      redirectRegex:
        permanent: true
        regex: "^https://bar.adathor.com/(.*)"
        replacement: "https://teams.live.com/meet/958209746513?p=QJ4Fyl4oIlGVxI4V"
    xyz-redirect:
      redirectRegex:
        permanent: true
        regex: "^https://openstorage.io/(.*)"
        replacement: "https://blog.adathor.com"
    authie:
      basicAuth:
        users:
          - "dataricecrispygoat:$2y$05$Kc/QaANDHuMS81EpuEf1xuOlg9.Tp79T7jeTULF4pimP0OwHBV4j2"

tcp:
  services:
    gitea-ssh:
      loadbalancer:
        servers:
          - address: "17.10.0.20:2222"
  routers:
    gitea-ssh:
      entryPoints:
        - "ssh"
      rule: "HostSNI(`*`)"
      service: gitea-ssh

