---    
  - name: Install required packages
    zypper:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    with_items:
      - mc
      - git
      - zsh
      - vim
      - cifs-utils
      - nload
      - yakuake
      - dkms
      - tmux
      - weechat
      - wget
      - nodejs
      - npm
      - automake
      - autoconf
      - gcc7 
      - gcc7-c++ 
      - make 
      - automake 
      - autoconf
      - gcc7-c++
      - vlc
      - clementine
      - python-pip
      - transmission-daemon
      - transmission-qt
      - ranger

  - name: Copy zshrc
    copy:
      src: .zshrc
      dest: /home/apinter/.zshrc

  - name: Full system upgrade
    zypper:
      name: '*'
      state: latest