---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/pihole: image
  labels:
    app: pihole-pod
  name: pihole-pod
spec:
  containers:
  - name: pihole
    image: docker.io/pihole/pihole:latest
    env:
    - name: ServerIP
      value: 127.0.0.1
    - name: TZ
      value: Asia/Jakarta
    - name: VIRTUAL_HOST
      value: pi.hole
    - name: PROXY_LOCATION
      value: pi_hole
    - name: WEBPASSWORD
      value: minad1234
    ports:
    - containerPort: 53
      hostIP: 10.222.0.1
      hostPort: 53
    - containerPort: 443
      hostIP: 10.222.0.1
      hostPort: 4443
    - containerPort: 80
      hostIP: 10.222.0.1
      hostPort: 8082
    - containerPort: 53
      hostIP: 10.222.0.1
      hostPort: 53
      protocol: UDP
    securityContext:
      capabilities:
        add:
        - CAP_NET_ADMIN
    volumeMounts:
    - mountPath: /etc/pihole
      name: etc-pihole-pvc
    - mountPath: /etc/dnsmasq.d
      name: etc-dnsmasq-pvc
  volumes:
  - name: etc-pihole-pvc
    persistentVolumeClaim:
      claimName: etc-pihole
  - name: etc-dnsmasq-pvc
    persistentVolumeClaim:
      claimName: etc-dnsmasq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-dnsmasq
  labels:
    app: pihole-pod
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole
  labels:
    app: pihole-pod
spec:
  accessModes:
    - ReadWriteOnce
