---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/podman_vol/pihole/etc-dnsmasq:z
    io.containers.autoupdate: registry
  labels:
    app: pihole-pod
  name: pihole-pod
spec:
  containers:
  - name: pihole
    image: docker.io/pihole/pihole:latest
    env:
    - name: TZ
      value: Asia/Jakarta
    - name: VIRTUAL_HOST
      value: pi.hole
    - name: PROXY_LOCATION
      value: pi_hole
    - name: ServerIP
      value: 127.0.0.1
    - name: WEBPASSWORD
      value: minad1234
    ports:
    - containerPort: 53
      hostPort: 53
    - containerPort: 443
      hostPort: 443
    - containerPort: 80
      hostPort: 8082
    - containerPort: 53
      hostPort: 53
      protocol: UDP
    securityContext:
      capabilities:
        add:
        - CAP_NET_ADMIN
    volumeMounts:
    - mountPath: /etc/dnsmasq.d
      name: home-podman_vol-pihole-etc-dnsmasq-host-0
    - mountPath: /etc/pihole
      name: home-podman_vol-pihole-etc-pihole-host-1
  volumes:
  - hostPath:
      path: /home/podman_vol/pihole/etc-dnsmasq
      type: Directory
    name: home-podman_vol-pihole-etc-dnsmasq-host-0
  - hostPath:
      path: /home/podman_vol/pihole/etc-pihole
      type: Directory
    name: home-podman_vol-pihole-etc-pihole-host-1
