---
  - name: Create Project dirs
    file:
      path: /home/apinter/Project/git
      state: directory

  - name: Clone dotconf repo
    git:
      repo: 'https://github.com/apinter/dotconf.git'
      dest: /home/apinter/Project/git
      clone: yes
