---
 - name: Change the hostname to inventory default
   hostname:
    name: "{{ inventory_hostname }}"

 - name: Change hosts file
   template: 
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
