---
  - name: Copy repo configruation
    copy:
      src: pacman.conf
      dest: /etc/pacman.conf

  - name: Full system upgrade
    pacman: 
      update_cache: yes
      upgrade: yes

  - name: Install required packages
    pacman:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items:
      - zsh 
      - vim
      - grub
      - efivar 
      - efibootmgr 
      - openssh 
      - sshfs 
      - cryptsetup 
      - lvm2 
      - git 
      - snapper 
      - reflector 
      - firewalld 
      - networkmanager 
      - network-manager-applet 
      - networkmanager-openconnect 
      - networkmanager-openvpn 
      - networkmanager-pptp 
      - networkmanager-vpnc 
      - firefox 
      - rhythmbox 
      - chromium 
      - vlc 
      - ffmpeg 
      - exfat-utils 
      - fuse-exfat 
      - a52dec 
      - faac 
      - faad2 
      - flac 
      - jasper 
      - lame 
      - libdca 
      - libmad 
      - libmpeg2 
      - libtheora 
      - libvorbis 
      - libxv 
      - wavpack 
      - x264 
      - x265 
      - xvidcore 
      - libdvdcss 
      - libdvdread 
      - libdvdnav 
      - dvd+rw-tools 
      - dvdauthor 
      - dvgrab 
      - p7zip 
      - unrar 
      - tar 
      - rsync 
      - cmus 
      - libreoffice-fresh 
      - alsa-utils 
      - xorg-server 
      - xorg-xinit 
      - mesa 
      - ttf-dejavu 
      - samba 
      - smbclient 
      - gvfs 
      - gvfs-smb 
      - xf86-video-intel 
      - xf86-input-synaptics 
      - screenfetch 
      - termite 
      - mc 
      - glances 
      - dmenu 
      - youtube-dl 
      - gnome-keyring 
      - htop 
      - transmission-gtk 
      - transmission-cli 
      - pulseaudio 
      - feh 
      - arandr 
      - pacman-mirrorlist 
      - unzip 
      - zip 
      - thunderbird 
      - phonon-qt5-vlc 
      - phonon-qt5-vlc 
      - phonon-qt4-gstreamer 
      - phonon-qt4-vlc 
      - phonon-qt5-vlc 
      - phonon-qt4-gstreamer 
      - phonon-qt4-vlc 
      - phonon-qt4 
      - phonon-qt5 
      - phonon-qt5-gstreamer 
      - okular 
      - archlinux-wallpaper 
      - geary 
      - st 
      - tmux 
      - epiphany 
      - baobab 
      - weechat 
      - lm_sensors 
      - mpc 
      - hddtemp 
      - nitrogen mpd 
      - ncmpcpp 
      - conky 
      - scrot 
      - mpd 
      - xfce4-power-manager 
      - pcmanfm 
      - thunar 
      - xfce4-notifyd 
      - nmap 
      - acpi 
      - net-tools
      - wireless_tools 
      - iw 
      - sysstat 
      - gparted 
      - dosfstools 
      - ntfs-3g 
      - nilfs-utils 
      - gpart 
      - mtools 
      - f2fs-tools 
      - btrfs-progs 
      - lxappearance 
      - compton 
      - gnome-font-viewer 
      - cmake 
      - mono 
      - cargo 
      - autoconf 
      - gcc 
      - w3m 
      - gst-plugins-base 
      - gst-plugins-good 
      - gst-plugins-bad 
      - gst-plugins-ugly 
      - gst-libav 
      - ffmpegthumbnailer 
      - yakuake 
      - virt-manager 
      - virt-install 
      - libvirt 
      - srm 
      - emacs
      - i3
      - plasm ked-applications

  - name: Enable services
    systemd:
      name: "{{ item }}"
      enabled: yes
    with_items:
      - firewalld
      - sddm
      - NetworkManager
  
