apiVersion: ENC[AES256_GCM,data:2j0=,iv:ZOcdjmPbjpoHwycuNoGi2iUxKTKQpxl/cru+xNkTCg4=,tag:Q6SRGJ9Oufd+WgbJt2QiCQ==,type:str]
kind: ENC[AES256_GCM,data:egqJ,iv:wagXVK40Yt6JZh/BbmwINdaIk8xkQ7ydwHLWcCy2iaM=,tag:+clR6FOVLw9cIEwscKHZeg==,type:str]
metadata:
    annotations:
        io.containers.autoupdate/traefik: ENC[AES256_GCM,data:3YMV2FA=,iv:SPj6kSWaKVjgoFiuT8LkTIqzYlfUcbyWVqhYODSTDU0=,tag:im/ZF6Q/zzGpyS5mSJcjww==,type:str]
    labels:
        app: ENC[AES256_GCM,data:iNZiAXRTR/sGaUw=,iv:k82/BgpEF/BsmMuAAWCYWuJyvIG85wAkj+QYHA1QxKo=,tag:FQZTVRHS396nItewonbMnw==,type:str]
    name: ENC[AES256_GCM,data:+HB+KLtWqlni9W0=,iv:5BkjsTz3CYbAjb6kBjQ4bGrgZCkRV7yQZdhImRUaIro=,tag:se02AjYiq3B7JjOqSWCF0g==,type:str]
spec:
    containers:
        - name: ENC[AES256_GCM,data:vbcEAgV+hQ==,iv:zMfu8lpzUqTRMxLycX09UCvx63pvRe4qL2VR2KDLQBo=,tag:0GDxoSGEhUaUWqDNfFLUEw==,type:str]
          image: ENC[AES256_GCM,data:IlC6vSueSU87dU7qVb0C9OATmRlgU5xp4XnzVIVbb8g=,iv:pCTbcBtb0nCPGXrqedLOyhdKzqx79mozKUBtwfe5jNo=,tag:EP2QguPZl2/d5ngXyyB7CA==,type:str]
          env:
            - name: ENC[AES256_GCM,data:4cR+VX5MLdD3JDtLKwTt6A==,iv:oI3tMcnGYNnvqnJA3tswm8rGZ+dxXxkEwjgI2t9fOns=,tag:aLHxEnD08UZ96EDsXHfdQA==,type:str]
              valueFrom:
                secretKeyRef:
                    name: ENC[AES256_GCM,data:bpPNkwnxmYU=,iv:nEIAh3sFKJa4oekw0l8FWQ4/YwHDNhF6G72F5SAXu50=,tag:QtLig0qZ2wPdrsdGMJmT1w==,type:str]
                    key: ENC[AES256_GCM,data:aKgx3fDwLEoY3YtygcFAqQ==,iv:bMubGu9EU41ezzL/xRcXFTkfxp2EhA4++nXa8A63s/Y=,tag:kh+DuxSR8V1FlV5bXPwj5Q==,type:str]
            - name: ENC[AES256_GCM,data:YCGojvy6nSXk9shw,iv:3mFxFjG74rpzJxswdZHdU0sPmbf9wQvpdiuI4799/+Y=,tag:M4ENHo1S68inBcvhnGxqHA==,type:str]
              value: ENC[AES256_GCM,data:VMDJQZEmmbcozTOeBw==,iv:486oENzOp6SyUMoTZU7/FsuCskq9b2z/bEakqQYQi0E=,tag:Yd6FpfeEtPIksuB0gJkFOw==,type:str]
          args:
            - ENC[AES256_GCM,data:Zj/Pt0A51utFNX09gFsthg==,iv:JphET4AlI/i3WJlvKI/EdUHnQlYblee/+Dm64mSEQg8=,tag:B8oV1VvKXQOguO9ORMIgPA==,type:str]
            - ENC[AES256_GCM,data:wv6ild3mG3jSvA259k0lFg==,iv:5hPdBRL/oSvwgwmPr+H4uot69mUgIx7IOm9SlTnZKus=,tag:EuFjT/GkmIQUyFSJOCrT6Q==,type:str]
            - ENC[AES256_GCM,data:0kQEu54q7DChg+c/VmmIaQA5yO4=,iv:f2DWJwfUgdPSUXZKwZmiqgoz3w+XcG+uCN8k82hhlas=,tag:7XcqYwhMPyhZ7tnbQt4A6A==,type:str]
            - ENC[AES256_GCM,data:ui0f3R6nOhB8MHYmYBg3QKov6mqA,iv:UObqtfutDSJs3OOS2lQb0V06ROuKTWwLFaj0WadehHI=,tag:GSckUAti2DpfzedAYWpd2w==,type:str]
            - ENC[AES256_GCM,data:nkbVR3pgxgLFUwHzo5ssqJb2i+E7RlQif7AeXxZ2hg==,iv:kpklw/So86wEyCEuxNXQ6TrPEbjo5sz1dFhPzk7q29E=,tag:GAEI3BiMZUCHheLZPSeE0g==,type:str]
            - ENC[AES256_GCM,data:DYOMNsSVQ2ovD+YOhRiEvEtTFLdtH4xf0rLhWKKS,iv:qM3QnQx2OCcdBWEdx564O31PPmlUSv9A7WSVJ40uJ6s=,tag:SkiqWZ5N5Syvcocu+fB8DA==,type:str]
            - ENC[AES256_GCM,data:t5US9klQz2OUmXLe60pMDcxu8UlHP6pxLAgGGPaLhHGBtajNYHs+ukRcb0pS59He+Wii7ZFmlNg=,iv:Cp6Y1PGNp8IufrYwM6M7XRowgCNHwnbysTVe99JRkZQ=,tag:uCyPNEtZxhhQZjor8NHIIw==,type:str]
            - ENC[AES256_GCM,data:i3maFJg4jp8c3Q6WXId6tx9BtAQvGkJIMOJB2+AAoLKneaaN8+QFY9WvE3iew6O86fzlpPy8D4oJGJeX,iv:5pMF5k8ZuNv/u3BYa89WOyPrj0WdEgdYyd01nND7Ljg=,tag:HcOHnYqu/TJkjot0/NXKHQ==,type:str]
            - ENC[AES256_GCM,data:wGnchYwyNdl3XNs2wnkZjlVmF+JMgDSjnA9eQNT7E0grEOM2DCwZKTeA//cFGNEZ6hJ69MGa2oUp/gIwiUs=,iv:uMEU1HDgpsjqBeTE5rxsOr3yqFLzmV0l5VPw9MYvxWA=,tag:mk3+tPZOhsBQhOVBYseO7w==,type:str]
            - ENC[AES256_GCM,data:Y35AqrvSr07Fq68GgXSNdyybFSqolmV8BGzrOEDRrB4=,iv:S+DxdBE0Q9rVUG22txu8JVzM726YUiaju+yoPIc/Oks=,tag:CCMvv599cYvbI7Dl1EFVuA==,type:str]
            - ENC[AES256_GCM,data:57VuI51zntfrKhZvC/SWFto8kiusHRsscr5xqUGHPaN5D9CJof5MYNpq/q3f4YAbbHi9,iv:gjzn9citm165+uqQ8ec1eIVpKwYhfdLkxwPfIZMYldI=,tag:+VBfJhwT8XCwNUZYwCgvUw==,type:str]
            - ENC[AES256_GCM,data:9xH0SlduXlFq3s8KPuegSUrnl5sGyDD/CWlrFNXS28ot028il3SlUpZlXfsKqntEbVDGAwOCk42eaNyo2z7WPA==,iv:/9P/3HXXo/QIJ0puHV+hVWuhfuj0tDx3tVtDumyDm6g=,tag:O7GXZICymEQkLAVpuK3aOA==,type:str]
            - ENC[AES256_GCM,data:Y3oYi7tn90iM2k/BxAEA/BIUQVZTC6kxGKA5dWwRR2FPBBtIac4yHwiYyVoyr1bfNee8UF3vxLULkaH5lTed0g==,iv:vz72weZVAAdALVH0BSzLyR6tkj3yLWQ9nr/dXnpPHMw=,tag:q4vuw2sctnmzB+8qw3qKSQ==,type:str]
            - ENC[AES256_GCM,data:iDEbsUfRUOg1LLgz/iOhS6vCGaji58rABA6os1JAcyNRBv8UJWMDOsHF9oENrwqj472xuklqsJfluYCyUh5NYYs=,iv:JjiPImYZ4RpBQRDKdUAep96Pc4iLPKJl91ZOO6VDiHw=,tag:xmKkkoLbcUzzL0WEXtJtSA==,type:str]
            - ENC[AES256_GCM,data:BI4Zcf2zAv3dIWsOuUwGnFniWdzoYCzfY9AqmYJd5ASg6e43rkPP4HJzcYePzpdo4K7xlsO3QEhnTeZVX3WFtpysNyY1laQLoHFRmDUc/KHXoWIWf14wfxHX9RYgrr9dSBsnEbzZnLQggV7i/OEM5VOWN3ofEUDjCeOSrNWJLN/Az/JSnLpOn+dAv91NUq9yc5R1ikXAEzm+9ayVx7seUbudLH8Grl3JlpUXFoZpYu9mzc3C9DCE1qJC+wjF3RQtg2L1duimcOHQEeNYi5hHgrgS1JXvxCFwxU8iLCXXvXpWwXYkdAYw7HhTLVkAxHR8VRfirqFpv1ynAeTOWYzZ8KbB6D15fRE3rPV4+HviQODrEsJmiw2ILwZ+2XtxqTpzDWVeZyeuduwFEcDAUuee/RtybNb6pj5XZyxVOWgagkxrxk5WOKt2UPm35ktfGds7IKwLI4hTEOnicohLAmZMLZL5EZqnZXhB5mKAARNdYh6Ww1yofYTYZfu7Cu3lje0=,iv:3Bmj9K+jjDyVR5vUSsSIk5rkR+efrtuh2DIb+X6+ZfE=,tag:251UoPCxJrokCQCU20vocA==,type:str]
            - ENC[AES256_GCM,data:/BUpbu7/Q7Ad4vahBgt7oXVh7/m+WvitQl+pGtLlzDqvPd9eF2GlPtkx9ywwYL8SmcIhJ/NETUzrvg==,iv:ShApGvbkPawKFsfIqdqhkg5a3rETjObbFF0e4RwwcAw=,tag:iL1BOAJjx7FvwcbTfAjOzw==,type:str]
            - ENC[AES256_GCM,data:JdLfnujHh+jIy87Zm/d/4HXHGrX91NI2cbtmupiAySpBOyPgTW+r7NC2OI9Eai0/mbaevuqnVYtw1POoZtKFf3OPnYSHR76LJg==,iv:iPd11WpHiqlhwWgZS774K0rTaUeSlVQgHyDal2YxqF4=,tag:JrixFv836j37GMVmnqUVPA==,type:str]
            - ENC[AES256_GCM,data:6m87KIdNCmfAVOdzkyrMaBQIjPQSWsc18CekONdBtDWyp3uIInbpFWg2QxVUxdlDxW3yLa7tS4aG8+SE,iv:zKxnVp4O458dnPf80xpyvVyJVxtWjLj5UeNSL5uPwFw=,tag:YBTH47Xlsdhzk3U0XhKSnw==,type:str]
            - ENC[AES256_GCM,data:EwMV26PcmWh+cZwTIYPbDJJjFE1BDiARLsp/u3TmT4Tq+/xfmRw2jbLKYcalm3gWkt4iMuWSG6tFD9JSfJT+eEA2hBvnhWE=,iv:5NB2Qcz/LSwZotxddL0IfA+dwybAuq80al/xngDxvAE=,tag:WZeOO6vG0QtqgFGjNRwi+Q==,type:str]
            - ENC[AES256_GCM,data:8cTF4MwPJAe389WczT7RuEbNjRTVIkJyxBUQql/NhOxgbpb1buJOP6ktu7n7VMCf7gqXkw0JqEn3wQ==,iv:ZCESPcfziNzWhxhE2oWyE2Zta2KCiZa1Hp7KGiy80LM=,tag:5t87TBWfD6yupza3l5/fyA==,type:str]
            - ENC[AES256_GCM,data:O0/lxkmgKc9KhlvhK+fvqb1icY7ivYkGRzUkhGlimDBeh7scnyjQyqWdj+yP,iv:VdUi0al2Cy5U4PRgsNW5H0XgENfmXp8yknpA4XH6NF8=,tag:F9r8mDgxebWsKDPKyc9UWw==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:oE0=,iv:kudBOq4FSJ29cd5jgSn5AYQ3p37ke9wocEhEIp2loJs=,tag:DFqQdYCI+dIyG2HfgF1hag==,type:int]
              hostPort: ENC[AES256_GCM,data:zww=,iv:NvXdhSHTdfUbhmVVXTYPKdV5p8qqBDI50Sx/rzFiEqM=,tag:TYYYW/ChhqS7rwVlM857Zw==,type:int]
            - containerPort: ENC[AES256_GCM,data:NhE+,iv:7KVXnmbw2dMiksiP4C6DbT2IrX/sJq3sPtnxFkEgzMU=,tag:hr9x9CiRmc/L72v16rtWOA==,type:int]
              hostPort: ENC[AES256_GCM,data:Dt9G,iv:eiXWpxkwbx7CenyiYr19EG9HhNUaeV2C3C163JzABcQ=,tag:RL6zcNyKI009rloL1YuPCQ==,type:int]
            - containerPort: ENC[AES256_GCM,data:MPl8pQ==,iv:h+m/1sqSm1HTE6MGZUS1FATmrt8BTFn+wzponyJAmUA=,tag:Ex8qo+jxqmg+azZ2BMGAlg==,type:int]
              hostPort: ENC[AES256_GCM,data:4Qlv9A==,iv:nfU2VoGE7lgVM8f/hIYo4cXkNsnUm7Pdj5dS49Q9JUE=,tag:2+60/jbcyvYQvaF4JxizKw==,type:int]
          volumeMounts:
            - mountPath: ENC[AES256_GCM,data:iuGgd5bOMw==,iv:IGHrLgkO5XIyuYiBtmpeDqRzB97dg8O7PwzUC7J2ofI=,tag:rcTrOJE4nHZ7KJbOi6FEEQ==,type:str]
              name: ENC[AES256_GCM,data:MjAQWK2BX1yPJA==,iv:C1DuU14uF7pnHMgRDrVMqvFj27Jl677MqFins+YIA/A=,tag:FHuy5scCkbCTKlvMCO+opQ==,type:str]
            - mountPath: ENC[AES256_GCM,data:zSeH/qRP1e10fQkX,iv:ApTp49/D/oDWXoYrQsktf5FFvOtEwJLiLuIOORbRM6w=,tag:26T2tGWYbHMM0L2Tq/EEBw==,type:str]
              name: ENC[AES256_GCM,data:T1ENMPRcfXBKGvq6oHdf,iv:rQM2PmVHtzsuAhKbo1wW/23R/KnZ7W9T7uzq+qKczIw=,tag:dBkHsM3WCbCBDw9b0vDmjw==,type:str]
    volumes:
        - name: ENC[AES256_GCM,data:mkT6MU2c1MnP8A==,iv:oqqYyahfb0j+dgIY57pwzpLNuSNykKdTpVCdY2ueQMc=,tag:gm7uV2OVKhoMSLdi4WrIyQ==,type:str]
          persistentVolumeClaim:
            claimName: ENC[AES256_GCM,data:ikt4yGzeZ5e5GqZpy6A=,iv:CTydvLJ/eLq2QNJP/RBnrb+bewH7S7KF81Sl8O+Xsgo=,tag:Zu1Hpez95Kh3YBjbHzRScQ==,type:str]
        - name: ENC[AES256_GCM,data:18RQ5VTnhnu62wLW2uZx,iv:IXDuensxF4fdXO7SVts4Dacd9b6EIqaZXZbyacceLz0=,tag:5y190Z/4j86GfwK3F1dVHQ==,type:str]
          persistentVolumeClaim:
            claimName: ENC[AES256_GCM,data:hSsrXzIA6qdMueY=,iv:E7AOJEXVGi5C4B7SuO0IC5edftHmAPbbnSGAvSYzMEA=,tag:gUYFpZy99czP4SrMrYG6rQ==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTnM0Z0xTSUE5d2JYQ0pW
            ZTRvRktxVTBjbEM0dDJMdDZ3K00zQWx0dkdrCmhUa2l6aUVxblp6TG5VZDJZdG8y
            T29ya0tueUdLOEl3RVcxeXNpQW41ak0KLS0tIFp5cGx3aDZFQ0pQWWlqYjNuRVMr
            RTY4Nm5kSmg4K2x6OVhSTUx3eFN2UW8KQdeqLneP0ITWo2FM4RnZtJsH3FmKTZ+y
            0o443T+w/QrHyc7KvV0WtDw0qCu0Zziio2e2nXN9JocU6LquflotzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T00:59:45Z"
    mac: ENC[AES256_GCM,data:JHQYvSc+IN7uJpGEoHgnSV2bTxU62QfKAgjEiEHujuyja6I7wpboCfPCtH//3QYyDcG7FpDvXgZAetfd2TDcs06oo0OD0vDRpYWMA+kfwQxAyYqsSnUeQED41T8eK88f+XwZsxBKCYCtSAOlWuCS4iZk5qxhnf4KVVEdaLMX5hQ=,iv:SBql7okxEDyDUsey6T4j39Y7Z8WaCh6JaCQgC9eN800=,tag:BnUJ8wbTl0KDVw0L+s+WnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Lww=,iv:ZFnLV4czEkykkPvXYpGM1wD5RYCJyrbyqV9aUplUSSE=,tag:tkZmeZCTLEHw4onf0ROz8Q==,type:str]
kind: ENC[AES256_GCM,data:/8bwxB9w6W2u1MHaCy9LV4AFdKHZ,iv:rVtPjyjWOiOILXnekBzE84AENUl1tMTSXt5E8IaTXuA=,tag:5kmn4VWRvmL7FsQmtSjPqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3aHa+Jm+78gUpinP54o=,iv:KQmYSxMY+jrGYt6qHMCPxkOFeUJYr04g9cFB+5eH1Y0=,tag:KjbiOqjgWqRxrjIe/gq0PA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:iuKdu1TtGo51icQ=,iv:yF0uGfNohVF4JEwbvjFQg6eEaxIzCg3ErgmyKHzgD5Y=,tag:N2Ze3ZSSEGfiNa1QcWhayQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:6p05coI50FzH+GJg3w==,iv:t9wnKp3gHhU67TmQ252/wK1R1CRYZvjqA8Op+vGTb6E=,tag:ODoxay+yo8mmzn0PpQBd8g==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTnM0Z0xTSUE5d2JYQ0pW
            ZTRvRktxVTBjbEM0dDJMdDZ3K00zQWx0dkdrCmhUa2l6aUVxblp6TG5VZDJZdG8y
            T29ya0tueUdLOEl3RVcxeXNpQW41ak0KLS0tIFp5cGx3aDZFQ0pQWWlqYjNuRVMr
            RTY4Nm5kSmg4K2x6OVhSTUx3eFN2UW8KQdeqLneP0ITWo2FM4RnZtJsH3FmKTZ+y
            0o443T+w/QrHyc7KvV0WtDw0qCu0Zziio2e2nXN9JocU6LquflotzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T00:59:45Z"
    mac: ENC[AES256_GCM,data:JHQYvSc+IN7uJpGEoHgnSV2bTxU62QfKAgjEiEHujuyja6I7wpboCfPCtH//3QYyDcG7FpDvXgZAetfd2TDcs06oo0OD0vDRpYWMA+kfwQxAyYqsSnUeQED41T8eK88f+XwZsxBKCYCtSAOlWuCS4iZk5qxhnf4KVVEdaLMX5hQ=,iv:SBql7okxEDyDUsey6T4j39Y7Z8WaCh6JaCQgC9eN800=,tag:BnUJ8wbTl0KDVw0L+s+WnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:wvE=,iv:ZIGja8KH9wBiePY3sSig/JZamkMEE3L7yhzZhdZWz00=,tag:XyRDGSQ/K3i4e33UF+7Tfg==,type:str]
kind: ENC[AES256_GCM,data:Jpmfo1+eYfpbZ1bL8Iyk25IiTO7w,iv:U/yCL93XEzk1WAVz8Ez/AUzyaT1dGBZEVujjmYZHcHg=,tag:V9xs8iBYcwlw4f+RXsvUUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6wc6Dw6Bf/poykg=,iv:dl9opSHyCOV2QWR+aadk2NGFsahF4i7FLyhAWjsqI+4=,tag:Lxm+HRSi1rYxHrEG0+YvFQ==,type:str]
    labels:
        app: ENC[AES256_GCM,data:myeiFZ5CN1VJBXk=,iv:17aauC3yJmlTYMHactFjeJuyw4MzLn4g23hHnifJIWc=,tag:x2m57lyiQtDtOu62fHSFzA==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:tQSJIaraWIWX7wClag==,iv:fFVtFJyT89ppNXBRueA/gLE8G6qRfxKmKJ2zDCJb9/E=,tag:4fIBdlRRC23A39BAUQY+uA==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTnM0Z0xTSUE5d2JYQ0pW
            ZTRvRktxVTBjbEM0dDJMdDZ3K00zQWx0dkdrCmhUa2l6aUVxblp6TG5VZDJZdG8y
            T29ya0tueUdLOEl3RVcxeXNpQW41ak0KLS0tIFp5cGx3aDZFQ0pQWWlqYjNuRVMr
            RTY4Nm5kSmg4K2x6OVhSTUx3eFN2UW8KQdeqLneP0ITWo2FM4RnZtJsH3FmKTZ+y
            0o443T+w/QrHyc7KvV0WtDw0qCu0Zziio2e2nXN9JocU6LquflotzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T00:59:45Z"
    mac: ENC[AES256_GCM,data:JHQYvSc+IN7uJpGEoHgnSV2bTxU62QfKAgjEiEHujuyja6I7wpboCfPCtH//3QYyDcG7FpDvXgZAetfd2TDcs06oo0OD0vDRpYWMA+kfwQxAyYqsSnUeQED41T8eK88f+XwZsxBKCYCtSAOlWuCS4iZk5qxhnf4KVVEdaLMX5hQ=,iv:SBql7okxEDyDUsey6T4j39Y7Z8WaCh6JaCQgC9eN800=,tag:BnUJ8wbTl0KDVw0L+s+WnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:pFw=,iv:EJIJvGkNgVKT9Bm18KY22L0ISuMC3BTa9tbxbRLdH7E=,tag:UlK67eXq6/7JQSUs2ARMWg==,type:str]
kind: ENC[AES256_GCM,data:knBxsrBY,iv:zVAsWBlG160+vgvtyjVYNoaa6Km4adraBvRoS/cR+Eg=,tag:+8LjiogOawSwUlM8lk/eZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QfjB9Iyv9+s=,iv:6hDBr8Xkuo3dnkSAV2DCzCkHlgef1PRPqCwhVlrSHew=,tag:UU4h6hkwvcx1sAKnVmvdlQ==,type:str]
data:
    cloudflare-token: ENC[AES256_GCM,data:MP61Gb+YCi68eV5apLo+UbBrhnXlytNysEICjNXsTtnj/Ev4kHiP7TqqRHqGCmROAWqIh/IucdQ=,iv:vhaKdrY7G05dyJRm7HNEeECNXbOH45ZCQaGnTRW2dhs=,tag:LWF1D6sGFIH4jvVbQoqYHg==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTnM0Z0xTSUE5d2JYQ0pW
            ZTRvRktxVTBjbEM0dDJMdDZ3K00zQWx0dkdrCmhUa2l6aUVxblp6TG5VZDJZdG8y
            T29ya0tueUdLOEl3RVcxeXNpQW41ak0KLS0tIFp5cGx3aDZFQ0pQWWlqYjNuRVMr
            RTY4Nm5kSmg4K2x6OVhSTUx3eFN2UW8KQdeqLneP0ITWo2FM4RnZtJsH3FmKTZ+y
            0o443T+w/QrHyc7KvV0WtDw0qCu0Zziio2e2nXN9JocU6LquflotzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T00:59:45Z"
    mac: ENC[AES256_GCM,data:JHQYvSc+IN7uJpGEoHgnSV2bTxU62QfKAgjEiEHujuyja6I7wpboCfPCtH//3QYyDcG7FpDvXgZAetfd2TDcs06oo0OD0vDRpYWMA+kfwQxAyYqsSnUeQED41T8eK88f+XwZsxBKCYCtSAOlWuCS4iZk5qxhnf4KVVEdaLMX5hQ=,iv:SBql7okxEDyDUsey6T4j39Y7Z8WaCh6JaCQgC9eN800=,tag:BnUJ8wbTl0KDVw0L+s+WnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
