apiVersion: ENC[AES256_GCM,data:29Y=,iv:xET5TJvXYwldrm3eHwBP+ZMcH1+Lnja9nHOOAH3Ptc0=,tag:xsjNMCYUt+hqWSTysvKjig==,type:str]
kind: ENC[AES256_GCM,data:/Xjs,iv:88adWjlpXX0v+NirrpS1x30xYv340J6qAZEmz2SYFO8=,tag:lAtCHPMbLiUckbqEPlb72A==,type:str]
metadata:
    annotations:
        io.containers.autoupdate: ENC[AES256_GCM,data:PsDTwKAp+38=,iv:dHK/U7XHfXWstfKrlfdj92XDQZ6DrtBv0GNXjJR4Jm0=,tag:c94XRutWsXKb1XjgV6LWMg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:n8LV2h63eAyiXg==,iv:Ugp1rDc3o+kZ51l63vBzfTtvGT15+0TUsVSVG4LYPbU=,tag:qj99c3xbYobJR+KDtKqHAw==,type:str]
    name: ENC[AES256_GCM,data:6ruKN72Wow1lYw==,iv:3Kigqq0wS8VXhl7uG8MONLk1ZZOLFQQWerhUfHxRwkQ=,tag:J35OI57HFHgPIXBcr/THjg==,type:str]
spec:
    containers:
        - name: ENC[AES256_GCM,data:0rGK3s5objn7+7c=,iv:nJQL4jGloFnBJdZhAJ+HE2MUdEBjaD+MnfEAhaxMl2w=,tag:sJ/GMbRXno/cSGGS/bWkjg==,type:str]
          image: ENC[AES256_GCM,data:wKKzq37x3nzliB8IV7OxskLIMrOVS1QkpgiXAuJ4yZA=,iv:VI0BTD0flK20Kz/d2fwOGYIsHvqhGWD2cotlAzLFpFA=,tag:14uRMe5fiP6ZQeuH4kWhOA==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:3KODJw==,iv:rL/LvgZCcAc1/qFISlQOxK6mPjC3wDf3tsJ/JI+4EZI=,tag:25OSN2h2rF0HuHhF26p1rg==,type:int]
              hostIP: ENC[AES256_GCM,data:Jvf8Lutopj42J1sJKQ==,iv:BQecMQY0qHy8+oRANN1sSr/OypEqHpgu/Sauz86yxA4=,tag:Ac434nGKvrWo85a4u9vZFg==,type:str]
              hostPort: ENC[AES256_GCM,data:GxcbkA==,iv:EJH4fzSrPkzkrkxzLKFxOL3HsESy/yNbcew6QX4So4o=,tag:p4gQZKW06cLgtSavBO51+A==,type:int]
          volumeMounts:
            - mountPath: ENC[AES256_GCM,data:fsq4Akuq5oof,iv:hpP3mx+y1ijDrPjXQdtSJgIY6NrXq5Q+Z0skK0r+Yeg=,tag:AIMZhbK12cfQCNwmO7CTPw==,type:str]
              name: ENC[AES256_GCM,data:rPZ+l4d3oDztLA==,iv:eVtegBCKdAILFluxAVNPPNzASvyYZqij/hMk5HHpSOk=,tag:EdnzvcgDkDxPuov2a9VP1A==,type:str]
    volumes:
        - name: ENC[AES256_GCM,data:meRnhVxybbCbYg==,iv:gDBjs5sZRnCUZtcBsyPQLMh5XkZBeUfCL2nLA9vs/KU=,tag:iMtoRyF0XrlBVXrOTjO67g==,type:str]
          persistentVolumeClaim:
            claimName: ENC[AES256_GCM,data:z7ILywfF,iv:wPZXsaqqPOOlz12xfi1QoH06rtUESTDku8fCaLFXt0U=,tag:Z2tbkQuc7O+1NK82cIcaFw==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4akVvbVM1cGRaVlhIa3M3
            c0JRNldxYXJTSE50RDZHOG52RTJKVEZ5d3l3Cks5YXVHREpKOGNvQnBhYU00S05Q
            MWsrZ0N0Rm0rT0lmTUY3bEN0L0VHcHMKLS0tIHlRUHlQT3JLU1g0dTluR0tEVWJQ
            S1h3bmdmd2tlem1lNzlyTHV5cGQ5QUkK/5k9GRfraiH8VGau4c8bx3h7IvGLUwyT
            b2ReI4iAj7cE9+U5aSnh0bbay6zaTH8uxpQViCIn5AsJVuxtBc4p2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T00:59:45Z"
    mac: ENC[AES256_GCM,data:VtYT1B2uTrdrMVSpxyvTIO4wzi7nDZTRmjYewoetpBSlfbhHY67oqwflkJC3n1+t4oe/u65OuFhl8wQIXts9bR1wn83wM/MdYBIlfBCrpg7yhG6oeQtekbbEgIs/+lCOzcIL3BDTmpBgbdES2qCyoL8UTjsUanvgxQkiLVI3Ddo=,iv:vypVvEmx3CrsunkkZFXZIc9lJDYpExbuODCVTWdife0=,tag:g3Yi7yKBHJp7LRnIwI2Shg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:i0c=,iv:cds4Q0msas7OV0E3D+aCfTb3bqePEMoU8yKHLBx1adk=,tag:IWUWeav3mlO0Bc+G58N2+w==,type:str]
kind: ENC[AES256_GCM,data:my2K9QRfL4ZwfoAseyOTAXNmzwNW,iv:KF/9QCHNDpCJ9RyryK5uCzeW0V24/hkUusFIKpPikRM=,tag:Tns9vMnmOd3FCsicMr3wqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FdEyw/Vv,iv:l7ZtYTBwk6eoBGSPCt1/g1Yx6CgjhPiTDqLJum8fms8=,tag:eleaGEW3xxRiKwOLkyTFNg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:L6/NaSGmZKc5MQ==,iv:N1EWKZK2CrzvHhpJc1ImqQO5bQy8ozzUVJXfY5FZlcs=,tag:k4Ev2oFm5gcTtS44RyCFaw==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:sZYecPAxXL6+4ZoSzg==,iv:bpP1W4d3s7mnyIUF0zcfEGciVRktTxsH9Z4xOJFLzjU=,tag:vxheoZUN2wutlzFNtMIopg==,type:str]
sops:
    age:
        - recipient: age1dnmrt6dak3mkfwe8tdnn3vtnpdwekw75cru072g5zpgfr2tv8ycqtcrfat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4akVvbVM1cGRaVlhIa3M3
            c0JRNldxYXJTSE50RDZHOG52RTJKVEZ5d3l3Cks5YXVHREpKOGNvQnBhYU00S05Q
            MWsrZ0N0Rm0rT0lmTUY3bEN0L0VHcHMKLS0tIHlRUHlQT3JLU1g0dTluR0tEVWJQ
            S1h3bmdmd2tlem1lNzlyTHV5cGQ5QUkK/5k9GRfraiH8VGau4c8bx3h7IvGLUwyT
            b2ReI4iAj7cE9+U5aSnh0bbay6zaTH8uxpQViCIn5AsJVuxtBc4p2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T00:59:45Z"
    mac: ENC[AES256_GCM,data:VtYT1B2uTrdrMVSpxyvTIO4wzi7nDZTRmjYewoetpBSlfbhHY67oqwflkJC3n1+t4oe/u65OuFhl8wQIXts9bR1wn83wM/MdYBIlfBCrpg7yhG6oeQtekbbEgIs/+lCOzcIL3BDTmpBgbdES2qCyoL8UTjsUanvgxQkiLVI3Ddo=,iv:vypVvEmx3CrsunkkZFXZIc9lJDYpExbuODCVTWdife0=,tag:g3Yi7yKBHJp7LRnIwI2Shg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
