if status is-interactive
    # Commands to run in interactive sessions can go here
function fish_greeting
end

set -g theme_display_docker_machine yes
set -g theme_display_k8s_context yes 
set -g theme_display_virtualenv yes
set -g theme_display_user ssh
#set -g fish_prompt_pwd_dir_length 0
set -g theme_color_scheme dark
set -g theme_display_git yes
set -g theme_display_hostname ssh
set -g theme_display_date no

set -gx GPG_TTY (tty)

## XDG vars
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

## Envs
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config 
export AZURE_CONFIG_DIR=$XDG_DATA_HOME/azure
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export CARGO_HOME="$XDG_DATA_HOME"/cargo 
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
export TMUX_CONF=~/.config/tmux/tmux.conf
export EDITOR=vim
export VISUAL=vim
export GPG_TTY=$(tty)

## NIX stuff
set NIX_LINK $HOME/.nix-profile
export NIX_SSL_CERT_FILE=/etc/ssl/ca-bundle.pem

## Gcloud
# source /home/apinter/Downloads/google-cloud-sdk/path.fish.inc  

## PATH
export PATH=/sbin:/usr/sbin:/usr/local/sbin:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/home/apinter/.local/bin:/home/apinter/.local/bin:/snap/bin:$HOME/.local/share/flatpak/exports/bin:$XDG_DATA_HOME/cargo/bin:$NIX_LINK/bin:$HOME/go/bin
alias z="z"

## Copilot
abbr copilot 'gh copilot'
abbr gcs 'gh copilot suggest -t shell'
abbr gce 'gh copilot explain'

## System Stuff
#alias sup="sudo zypper ref; sudo zypper dup -y -l; flatpak update --user -y"
abbr g "git" 
abbr grv "git remote -v"
abbr icat "kitty +kitten icat"
abbr cdgd "cd $HOME/Project/git/dotconf"
abbr dotfiles '/usr/bin/git --git-dir=$HOME/Project/git/dotconf/.git --work-tree=$HOME/Project/git/dotconf'
abbr ll "logo-ls -alh "
abbr ls "logo-ls"
abbr la "logo-ls -a"
abbr diablo2 "WINEARCH=win32 WINEPREFIX=~/.wine32 wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Diablo\ II/Diablo\ II.exe -w"
abbr tmux "tmux -f ~/.config/tmux/tmux.conf -u"
abbr cdp "cd ~/Project"
abbr cdh "cd ~/Project/Home"
abbr cda "cd ~/Project/Ansible"
abbr cdpa "cd ~/Project/Antavo"
abbr cdpag "cd ~/Project/Antavo/git"
abbr cdpagg "cd ~/Project/Antavo/git/GitlabClone"
abbr cdpaa "cd ~/Project/Antavo/ansible"
abbr cdg "cd ~/Project/git"
abbr cdd "cd ~/Downloads"
abbr cdm "cd ~/Media"
abbr e "vim"
abbr se "emacs -nw"
abbr tf "terraform"
abbr cdga "cd /home/apinter/Project/Antavo/git"
abbr dtw "distrobox-enter tw"
abbr dar "distrobox-enter arch-box"
abbr dubi "distrobox-enter ubuntu-box"
abbr dhe "distrobox-host-exec"

## Entertainment Stuff
abbr allmediaup "sudo mount 172.168.1.3:/shirayuki/Aurora /home/apinter/Project/Home/Aurora/Reno"
abbr allmediadown "sudo umount /home/apinter/Project/Home/Aurora/Reno"
abbr msce "rclone"
abbr sup "sudo zypper ref; sudo zypper dup; sudo flatpak update -y; flatpak --user update -y"
abbr dhe "distrobox-host-exec"

## Security Stuff
abbr knoxup "cryfs ~/.local/share/plasma-vault/Knox.enc ~/Vaults/Knox"
abbr knoxdown "cryfs-unmount /home/apinter/Vaults/Knox"
abbr agcp "export HTTPS_PROXY=localhost:8888"

## Kubectl stuff
abbr kx 'kubectx'
abbr k 'kubectl'
abbr ksys 'kubectl --namespace=kube-system'
abbr ka 'kubectl apply -f'
abbr ksysa 'kubectl --namespace=kube-system apply --recursive -f'
abbr kak 'kubectl apply -k'
abbr kk 'kubectl kustomize'
abbr kex 'kubectl exec -i -t'
abbr ksysex 'kubectl --namespace=kube-system exec -i -t'
abbr klo 'kubectl logs -f'
abbr ksyslo 'kubectl --namespace=kube-system logs -f'
abbr klop 'kubectl logs -f -p'
abbr ksyslop 'kubectl --namespace=kube-system logs -f -p'
abbr kp 'kubectl proxy'
abbr kpf 'kubectl port-forward'
abbr kg 'kubectl get'
abbr ksysg 'kubectl --namespace=kube-system get'
abbr kd 'kubectl describe'
abbr ksysd 'kubectl --namespace=kube-system describe'
abbr krm 'kubectl delete'
abbr ksysrm 'kubectl --namespace=kube-system delete'
abbr krun 'kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
abbr ksysrun 'kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
abbr kgpo 'kubectl get pods'
abbr ksysgpo 'kubectl --namespace=kube-system get pods'
abbr kdpo 'kubectl describe pods'
abbr ksysdpo 'kubectl --namespace=kube-system describe pods'
abbr krmpo 'kubectl delete pods'
abbr ksysrmpo 'kubectl --namespace=kube-system delete pods'
abbr kgdep 'kubectl get deployment'
abbr ksysgdep 'kubectl --namespace=kube-system get deployment'
abbr kddep 'kubectl describe deployment'
abbr ksysddep 'kubectl --namespace=kube-system describe deployment'
abbr krmdep 'kubectl delete deployment'
abbr ksysrmdep 'kubectl --namespace=kube-system delete deployment'
abbr kgsvc 'kubectl get service'
abbr ksysgsvc 'kubectl --namespace=kube-system get service'
abbr kdsvc 'kubectl describe service'
abbr ksysdsvc 'kubectl --namespace=kube-system describe service'
abbr krmsvc 'kubectl delete service'
abbr ksysrmsvc 'kubectl --namespace=kube-system delete service'
abbr kging 'kubectl get ingress'
abbr ksysging 'kubectl --namespace=kube-system get ingress'
abbr kding 'kubectl describe ingress'
abbr ksysding 'kubectl --namespace=kube-system describe ingress'
abbr krming 'kubectl delete ingress'
abbr ksysrming 'kubectl --namespace=kube-system delete ingress'
abbr kgcm 'kubectl get configmap'
abbr ksysgcm 'kubectl --namespace=kube-system get configmap'
abbr kdcm 'kubectl describe configmap'
abbr ksysdcm 'kubectl --namespace=kube-system describe configmap'
abbr krmcm 'kubectl delete configmap'
abbr ksysrmcm 'kubectl --namespace=kube-system delete configmap'
abbr kgsec 'kubectl get secret'
abbr ksysgsec 'kubectl --namespace=kube-system get secret'
abbr kdsec 'kubectl describe secret'
abbr ksysdsec 'kubectl --namespace=kube-system describe secret'
abbr krmsec 'kubectl delete secret'
abbr ksysrmsec 'kubectl --namespace=kube-system delete secret'
abbr kgno 'kubectl get nodes'
abbr kdno 'kubectl describe nodes'
abbr kgns 'kubectl get namespaces'
abbr kdns 'kubectl describe namespaces'
abbr krmns 'kubectl delete namespaces'
abbr kgoyaml 'kubectl get -o=yaml'
abbr ksysgoyaml 'kubectl --namespace=kube-system get -o=yaml'
abbr kgpooyaml 'kubectl get pods -o=yaml'
abbr ksysgpooyaml 'kubectl --namespace=kube-system get pods -o=yaml'
abbr kgdepoyaml 'kubectl get deployment -o=yaml'
abbr ksysgdepoyaml 'kubectl --namespace=kube-system get deployment -o=yaml'
abbr kgsvcoyaml 'kubectl get service -o=yaml'
abbr ksysgsvcoyaml 'kubectl --namespace=kube-system get service -o=yaml'
abbr kgingoyaml 'kubectl get ingress -o=yaml'
abbr ksysgingoyaml 'kubectl --namespace=kube-system get ingress -o=yaml'
abbr kgcmoyaml 'kubectl get configmap -o=yaml'
abbr ksysgcmoyaml 'kubectl --namespace=kube-system get configmap -o=yaml'
abbr kgsecoyaml 'kubectl get secret -o=yaml'
abbr ksysgsecoyaml 'kubectl --namespace=kube-system get secret -o=yaml'
abbr kgnooyaml 'kubectl get nodes -o=yaml'
abbr kgnsoyaml 'kubectl get namespaces -o=yaml'
abbr kgowide 'kubectl get -o=wide'
abbr ksysgowide 'kubectl --namespace=kube-system get -o=wide'
abbr kgpoowide 'kubectl get pods -o=wide'
abbr ksysgpoowide 'kubectl --namespace=kube-system get pods -o=wide'
abbr kgdepowide 'kubectl get deployment -o=wide'
abbr ksysgdepowide 'kubectl --namespace=kube-system get deployment -o=wide'
abbr kgsvcowide 'kubectl get service -o=wide'
abbr ksysgsvcowide 'kubectl --namespace=kube-system get service -o=wide'
abbr kgingowide 'kubectl get ingress -o=wide'
abbr ksysgingowide 'kubectl --namespace=kube-system get ingress -o=wide'
abbr kgcmowide 'kubectl get configmap -o=wide'
abbr ksysgcmowide 'kubectl --namespace=kube-system get configmap -o=wide'
abbr kgsecowide 'kubectl get secret -o=wide'
abbr ksysgsecowide 'kubectl --namespace=kube-system get secret -o=wide'
abbr kgnoowide 'kubectl get nodes -o=wide'
abbr kgnsowide 'kubectl get namespaces -o=wide'
abbr kgojson 'kubectl get -o=json'
abbr ksysgojson 'kubectl --namespace=kube-system get -o=json'
abbr kgpoojson 'kubectl get pods -o=json'
abbr ksysgpoojson 'kubectl --namespace=kube-system get pods -o=json'
abbr kgdepojson 'kubectl get deployment -o=json'
abbr ksysgdepojson 'kubectl --namespace=kube-system get deployment -o=json'
abbr kgsvcojson 'kubectl get service -o=json'
abbr ksysgsvcojson 'kubectl --namespace=kube-system get service -o=json'
abbr kgingojson 'kubectl get ingress -o=json'
abbr ksysgingojson 'kubectl --namespace=kube-system get ingress -o=json'
abbr kgcmojson 'kubectl get configmap -o=json'
abbr ksysgcmojson 'kubectl --namespace=kube-system get configmap -o=json'
abbr kgsecojson 'kubectl get secret -o=json'
abbr ksysgsecojson 'kubectl --namespace=kube-system get secret -o=json'
abbr kgnoojson 'kubectl get nodes -o=json'
abbr kgnsojson 'kubectl get namespaces -o=json'
abbr kgall 'kubectl get --all-namespaces'
abbr kdall 'kubectl describe --all-namespaces'
abbr kgpoall 'kubectl get pods --all-namespaces'
abbr kdpoall 'kubectl describe pods --all-namespaces'
abbr kgdepall 'kubectl get deployment --all-namespaces'
abbr kddepall 'kubectl describe deployment --all-namespaces'
abbr kgsvcall 'kubectl get service --all-namespaces'
abbr kdsvcall 'kubectl describe service --all-namespaces'
abbr kgingall 'kubectl get ingress --all-namespaces'
abbr kdingall 'kubectl describe ingress --all-namespaces'
abbr kgcmall 'kubectl get configmap --all-namespaces'
abbr kdcmall 'kubectl describe configmap --all-namespaces'
abbr kgsecall 'kubectl get secret --all-namespaces'
abbr kdsecall 'kubectl describe secret --all-namespaces'
abbr kgnsall 'kubectl get namespaces --all-namespaces'
abbr kdnsall 'kubectl describe namespaces --all-namespaces'
abbr kgsl 'kubectl get --show-labels'
abbr ksysgsl 'kubectl --namespace=kube-system get --show-labels'
abbr kgposl 'kubectl get pods --show-labels'
abbr ksysgposl 'kubectl --namespace=kube-system get pods --show-labels'
abbr kgdepsl 'kubectl get deployment --show-labels'
abbr ksysgdepsl 'kubectl --namespace=kube-system get deployment --show-labels'
abbr krmall 'kubectl delete --all'
abbr ksysrmall 'kubectl --namespace=kube-system delete --all'
abbr krmpoall 'kubectl delete pods --all'
abbr ksysrmpoall 'kubectl --namespace=kube-system delete pods --all'
abbr krmdepall 'kubectl delete deployment --all'
abbr ksysrmdepall 'kubectl --namespace=kube-system delete deployment --all'
abbr krmsvcall 'kubectl delete service --all'
abbr ksysrmsvcall 'kubectl --namespace=kube-system delete service --all'
abbr krmingall 'kubectl delete ingress --all'
abbr ksysrmingall 'kubectl --namespace=kube-system delete ingress --all'
abbr krmcmall 'kubectl delete configmap --all'
abbr ksysrmcmall 'kubectl --namespace=kube-system delete configmap --all'
abbr krmsecall 'kubectl delete secret --all'
abbr ksysrmsecall 'kubectl --namespace=kube-system delete secret --all'
abbr krmnsall 'kubectl delete namespaces --all'
abbr kgw 'kubectl get --watch'
abbr ksysgw 'kubectl --namespace=kube-system get --watch'
abbr kgpow 'kubectl get pods --watch'
abbr ksysgpow 'kubectl --namespace=kube-system get pods --watch'
abbr kgdepw 'kubectl get deployment --watch'
abbr ksysgdepw 'kubectl --namespace=kube-system get deployment --watch'
abbr kgsvcw 'kubectl get service --watch'
abbr ksysgsvcw 'kubectl --namespace=kube-system get service --watch'
abbr kgingw 'kubectl get ingress --watch'
abbr ksysgingw 'kubectl --namespace=kube-system get ingress --watch'
abbr kgcmw 'kubectl get configmap --watch'
abbr ksysgcmw 'kubectl --namespace=kube-system get configmap --watch'
abbr kgsecw 'kubectl get secret --watch'
abbr ksysgsecw 'kubectl --namespace=kube-system get secret --watch'
abbr kgnow 'kubectl get nodes --watch'
abbr kgnsw 'kubectl get namespaces --watch'
abbr kgoyamlall 'kubectl get -o=yaml --all-namespaces'
abbr kgpooyamlall 'kubectl get pods -o=yaml --all-namespaces'
abbr kgdepoyamlall 'kubectl get deployment -o=yaml --all-namespaces'
abbr kgsvcoyamlall 'kubectl get service -o=yaml --all-namespaces'
abbr kgingoyamlall 'kubectl get ingress -o=yaml --all-namespaces'
abbr kgcmoyamlall 'kubectl get configmap -o=yaml --all-namespaces'
abbr kgsecoyamlall 'kubectl get secret -o=yaml --all-namespaces'
abbr kgnsoyamlall 'kubectl get namespaces -o=yaml --all-namespaces'
abbr kgalloyaml 'kubectl get --all-namespaces -o=yaml'
abbr kgpoalloyaml 'kubectl get pods --all-namespaces -o=yaml'
abbr kgdepalloyaml 'kubectl get deployment --all-namespaces -o=yaml'
abbr kgsvcalloyaml 'kubectl get service --all-namespaces -o=yaml'
abbr kgingalloyaml 'kubectl get ingress --all-namespaces -o=yaml'
abbr kgcmalloyaml 'kubectl get configmap --all-namespaces -o=yaml'
abbr kgsecalloyaml 'kubectl get secret --all-namespaces -o=yaml'
abbr kgnsalloyaml 'kubectl get namespaces --all-namespaces -o=yaml'
abbr kgwoyaml 'kubectl get --watch -o=yaml'
abbr ksysgwoyaml 'kubectl --namespace=kube-system get --watch -o=yaml'
abbr kgpowoyaml 'kubectl get pods --watch -o=yaml'
abbr ksysgpowoyaml 'kubectl --namespace=kube-system get pods --watch -o=yaml'
abbr kgdepwoyaml 'kubectl get deployment --watch -o=yaml'
abbr ksysgdepwoyaml 'kubectl --namespace=kube-system get deployment --watch -o=yaml'
abbr kgsvcwoyaml 'kubectl get service --watch -o=yaml'
abbr ksysgsvcwoyaml 'kubectl --namespace=kube-system get service --watch -o=yaml'
abbr kgingwoyaml 'kubectl get ingress --watch -o=yaml'
abbr ksysgingwoyaml 'kubectl --namespace=kube-system get ingress --watch -o=yaml'
abbr kgcmwoyaml 'kubectl get configmap --watch -o=yaml'
abbr ksysgcmwoyaml 'kubectl --namespace=kube-system get configmap --watch -o=yaml'
abbr kgsecwoyaml 'kubectl get secret --watch -o=yaml'
abbr ksysgsecwoyaml 'kubectl --namespace=kube-system get secret --watch -o=yaml'
abbr kgnowoyaml 'kubectl get nodes --watch -o=yaml'
abbr kgnswoyaml 'kubectl get namespaces --watch -o=yaml'
abbr kgowideall 'kubectl get -o=wide --all-namespaces'
abbr kgpoowideall 'kubectl get pods -o=wide --all-namespaces'
abbr kgdepowideall 'kubectl get deployment -o=wide --all-namespaces'
abbr kgsvcowideall 'kubectl get service -o=wide --all-namespaces'
abbr kgingowideall 'kubectl get ingress -o=wide --all-namespaces'
abbr kgcmowideall 'kubectl get configmap -o=wide --all-namespaces'
abbr kgsecowideall 'kubectl get secret -o=wide --all-namespaces'
abbr kgnsowideall 'kubectl get namespaces -o=wide --all-namespaces'
abbr kgallowide 'kubectl get --all-namespaces -o=wide'
abbr kgpoallowide 'kubectl get pods --all-namespaces -o=wide'
abbr kgdepallowide 'kubectl get deployment --all-namespaces -o=wide'
abbr kgsvcallowide 'kubectl get service --all-namespaces -o=wide'
abbr kgingallowide 'kubectl get ingress --all-namespaces -o=wide'
abbr kgcmallowide 'kubectl get configmap --all-namespaces -o=wide'
abbr kgsecallowide 'kubectl get secret --all-namespaces -o=wide'
abbr kgnsallowide 'kubectl get namespaces --all-namespaces -o=wide'
abbr kgowidesl 'kubectl get -o=wide --show-labels'
abbr ksysgowidesl 'kubectl --namespace=kube-system get -o=wide --show-labels'
abbr kgpoowidesl 'kubectl get pods -o=wide --show-labels'
abbr ksysgpoowidesl 'kubectl --namespace=kube-system get pods -o=wide --show-labels'
abbr kgdepowidesl 'kubectl get deployment -o=wide --show-labels'
abbr ksysgdepowidesl 'kubectl --namespace=kube-system get deployment -o=wide --show-labels'
abbr kgslowide 'kubectl get --show-labels -o=wide'
abbr ksysgslowide 'kubectl --namespace=kube-system get --show-labels -o=wide'
abbr kgposlowide 'kubectl get pods --show-labels -o=wide'
abbr ksysgposlowide 'kubectl --namespace=kube-system get pods --show-labels -o=wide'
abbr kgdepslowide 'kubectl get deployment --show-labels -o=wide'
abbr ksysgdepslowide 'kubectl --namespace=kube-system get deployment --show-labels -o=wide'
abbr kgwowide 'kubectl get --watch -o=wide'
abbr ksysgwowide 'kubectl --namespace=kube-system get --watch -o=wide'
abbr kgpowowide 'kubectl get pods --watch -o=wide'
abbr ksysgpowowide 'kubectl --namespace=kube-system get pods --watch -o=wide'
abbr kgdepwowide 'kubectl get deployment --watch -o=wide'
abbr ksysgdepwowide 'kubectl --namespace=kube-system get deployment --watch -o=wide'
abbr kgsvcwowide 'kubectl get service --watch -o=wide'
abbr ksysgsvcwowide 'kubectl --namespace=kube-system get service --watch -o=wide'
abbr kgingwowide 'kubectl get ingress --watch -o=wide'
abbr ksysgingwowide 'kubectl --namespace=kube-system get ingress --watch -o=wide'
abbr kgcmwowide 'kubectl get configmap --watch -o=wide'
abbr ksysgcmwowide 'kubectl --namespace=kube-system get configmap --watch -o=wide'
abbr kgsecwowide 'kubectl get secret --watch -o=wide'
abbr ksysgsecwowide 'kubectl --namespace=kube-system get secret --watch -o=wide'
abbr kgnowowide 'kubectl get nodes --watch -o=wide'
abbr kgnswowide 'kubectl get namespaces --watch -o=wide'
abbr kgojsonall 'kubectl get -o=json --all-namespaces'
abbr kgpoojsonall 'kubectl get pods -o=json --all-namespaces'
abbr kgdepojsonall 'kubectl get deployment -o=json --all-namespaces'
abbr kgsvcojsonall 'kubectl get service -o=json --all-namespaces'
abbr kgingojsonall 'kubectl get ingress -o=json --all-namespaces'
abbr kgcmojsonall 'kubectl get configmap -o=json --all-namespaces'
abbr kgsecojsonall 'kubectl get secret -o=json --all-namespaces'
abbr kgnsojsonall 'kubectl get namespaces -o=json --all-namespaces'
abbr kgallojson 'kubectl get --all-namespaces -o=json'
abbr kgpoallojson 'kubectl get pods --all-namespaces -o=json'
abbr kgdepallojson 'kubectl get deployment --all-namespaces -o=json'
abbr kgsvcallojson 'kubectl get service --all-namespaces -o=json'
abbr kgingallojson 'kubectl get ingress --all-namespaces -o=json'
abbr kgcmallojson 'kubectl get configmap --all-namespaces -o=json'
abbr kgsecallojson 'kubectl get secret --all-namespaces -o=json'
abbr kgnsallojson 'kubectl get namespaces --all-namespaces -o=json'
abbr kgwojson 'kubectl get --watch -o=json'
abbr ksysgwojson 'kubectl --namespace=kube-system get --watch -o=json'
abbr kgpowojson 'kubectl get pods --watch -o=json'
abbr ksysgpowojson 'kubectl --namespace=kube-system get pods --watch -o=json'
abbr kgdepwojson 'kubectl get deployment --watch -o=json'
abbr ksysgdepwojson 'kubectl --namespace=kube-system get deployment --watch -o=json'
abbr kgsvcwojson 'kubectl get service --watch -o=json'
abbr ksysgsvcwojson 'kubectl --namespace=kube-system get service --watch -o=json'
abbr kgingwojson 'kubectl get ingress --watch -o=json'
abbr ksysgingwojson 'kubectl --namespace=kube-system get ingress --watch -o=json'
abbr kgcmwojson 'kubectl get configmap --watch -o=json'
abbr ksysgcmwojson 'kubectl --namespace=kube-system get configmap --watch -o=json'
abbr kgsecwojson 'kubectl get secret --watch -o=json'
abbr ksysgsecwojson 'kubectl --namespace=kube-system get secret --watch -o=json'
abbr kgnowojson 'kubectl get nodes --watch -o=json'
abbr kgnswojson 'kubectl get namespaces --watch -o=json'
abbr kgallsl 'kubectl get --all-namespaces --show-labels'
abbr kgpoallsl 'kubectl get pods --all-namespaces --show-labels'
abbr kgdepallsl 'kubectl get deployment --all-namespaces --show-labels'
abbr kgslall 'kubectl get --show-labels --all-namespaces'
abbr kgposlall 'kubectl get pods --show-labels --all-namespaces'
abbr kgdepslall 'kubectl get deployment --show-labels --all-namespaces'
abbr kgallw 'kubectl get --all-namespaces --watch'
abbr kgpoallw 'kubectl get pods --all-namespaces --watch'
abbr kgdepallw 'kubectl get deployment --all-namespaces --watch'
abbr kgsvcallw 'kubectl get service --all-namespaces --watch'
abbr kgingallw 'kubectl get ingress --all-namespaces --watch'
abbr kgcmallw 'kubectl get configmap --all-namespaces --watch'
abbr kgsecallw 'kubectl get secret --all-namespaces --watch'
abbr kgnsallw 'kubectl get namespaces --all-namespaces --watch'
abbr kgwall 'kubectl get --watch --all-namespaces'
abbr kgpowall 'kubectl get pods --watch --all-namespaces'
abbr kgdepwall 'kubectl get deployment --watch --all-namespaces'
abbr kgsvcwall 'kubectl get service --watch --all-namespaces'
abbr kgingwall 'kubectl get ingress --watch --all-namespaces'
abbr kgcmwall 'kubectl get configmap --watch --all-namespaces'
abbr kgsecwall 'kubectl get secret --watch --all-namespaces'
abbr kgnswall 'kubectl get namespaces --watch --all-namespaces'
abbr kgslw 'kubectl get --show-labels --watch'
abbr ksysgslw 'kubectl --namespace=kube-system get --show-labels --watch'
abbr kgposlw 'kubectl get pods --show-labels --watch'
abbr ksysgposlw 'kubectl --namespace=kube-system get pods --show-labels --watch'
abbr kgdepslw 'kubectl get deployment --show-labels --watch'
abbr ksysgdepslw 'kubectl --namespace=kube-system get deployment --show-labels --watch'
abbr kgwsl 'kubectl get --watch --show-labels'
abbr ksysgwsl 'kubectl --namespace=kube-system get --watch --show-labels'
abbr kgpowsl 'kubectl get pods --watch --show-labels'
abbr ksysgpowsl 'kubectl --namespace=kube-system get pods --watch --show-labels'
abbr kgdepwsl 'kubectl get deployment --watch --show-labels'
abbr ksysgdepwsl 'kubectl --namespace=kube-system get deployment --watch --show-labels'
abbr kgallwoyaml 'kubectl get --all-namespaces --watch -o=yaml'
abbr kgpoallwoyaml 'kubectl get pods --all-namespaces --watch -o=yaml'
abbr kgdepallwoyaml 'kubectl get deployment --all-namespaces --watch -o=yaml'
abbr kgsvcallwoyaml 'kubectl get service --all-namespaces --watch -o=yaml'
abbr kgingallwoyaml 'kubectl get ingress --all-namespaces --watch -o=yaml'
abbr kgcmallwoyaml 'kubectl get configmap --all-namespaces --watch -o=yaml'
abbr kgsecallwoyaml 'kubectl get secret --all-namespaces --watch -o=yaml'
abbr kgnsallwoyaml 'kubectl get namespaces --all-namespaces --watch -o=yaml'
abbr kgwoyamlall 'kubectl get --watch -o=yaml --all-namespaces'
abbr kgpowoyamlall 'kubectl get pods --watch -o=yaml --all-namespaces'
abbr kgdepwoyamlall 'kubectl get deployment --watch -o=yaml --all-namespaces'
abbr kgsvcwoyamlall 'kubectl get service --watch -o=yaml --all-namespaces'
abbr kgingwoyamlall 'kubectl get ingress --watch -o=yaml --all-namespaces'
abbr kgcmwoyamlall 'kubectl get configmap --watch -o=yaml --all-namespaces'
abbr kgsecwoyamlall 'kubectl get secret --watch -o=yaml --all-namespaces'
abbr kgnswoyamlall 'kubectl get namespaces --watch -o=yaml --all-namespaces'
abbr kgwalloyaml 'kubectl get --watch --all-namespaces -o=yaml'
abbr kgpowalloyaml 'kubectl get pods --watch --all-namespaces -o=yaml'
abbr kgdepwalloyaml 'kubectl get deployment --watch --all-namespaces -o=yaml'
abbr kgsvcwalloyaml 'kubectl get service --watch --all-namespaces -o=yaml'
abbr kgingwalloyaml 'kubectl get ingress --watch --all-namespaces -o=yaml'
abbr kgcmwalloyaml 'kubectl get configmap --watch --all-namespaces -o=yaml'
abbr kgsecwalloyaml 'kubectl get secret --watch --all-namespaces -o=yaml'
abbr kgnswalloyaml 'kubectl get namespaces --watch --all-namespaces -o=yaml'
abbr kgowideallsl 'kubectl get -o=wide --all-namespaces --show-labels'
abbr kgpoowideallsl 'kubectl get pods -o=wide --all-namespaces --show-labels'
abbr kgdepowideallsl 'kubectl get deployment -o=wide --all-namespaces --show-labels'
abbr kgowideslall 'kubectl get -o=wide --show-labels --all-namespaces'
abbr kgpoowideslall 'kubectl get pods -o=wide --show-labels --all-namespaces'
abbr kgdepowideslall 'kubectl get deployment -o=wide --show-labels --all-namespaces'
abbr kgallowidesl 'kubectl get --all-namespaces -o=wide --show-labels'
abbr kgpoallowidesl 'kubectl get pods --all-namespaces -o=wide --show-labels'
abbr kgdepallowidesl 'kubectl get deployment --all-namespaces -o=wide --show-labels'
abbr kgallslowide 'kubectl get --all-namespaces --show-labels -o=wide'
abbr kgpoallslowide 'kubectl get pods --all-namespaces --show-labels -o=wide'
abbr kgdepallslowide 'kubectl get deployment --all-namespaces --show-labels -o=wide'
abbr kgslowideall 'kubectl get --show-labels -o=wide --all-namespaces'
abbr kgposlowideall 'kubectl get pods --show-labels -o=wide --all-namespaces'
abbr kgdepslowideall 'kubectl get deployment --show-labels -o=wide --all-namespaces'
abbr kgslallowide 'kubectl get --show-labels --all-namespaces -o=wide'
abbr kgposlallowide 'kubectl get pods --show-labels --all-namespaces -o=wide'
abbr kgdepslallowide 'kubectl get deployment --show-labels --all-namespaces -o=wide'
abbr kgallwowide 'kubectl get --all-namespaces --watch -o=wide'
abbr kgpoallwowide 'kubectl get pods --all-namespaces --watch -o=wide'
abbr kgdepallwowide 'kubectl get deployment --all-namespaces --watch -o=wide'
abbr kgsvcallwowide 'kubectl get service --all-namespaces --watch -o=wide'
abbr kgingallwowide 'kubectl get ingress --all-namespaces --watch -o=wide'
abbr kgcmallwowide 'kubectl get configmap --all-namespaces --watch -o=wide'
abbr kgsecallwowide 'kubectl get secret --all-namespaces --watch -o=wide'
abbr kgnsallwowide 'kubectl get namespaces --all-namespaces --watch -o=wide'
abbr kgwowideall 'kubectl get --watch -o=wide --all-namespaces'
abbr kgpowowideall 'kubectl get pods --watch -o=wide --all-namespaces'
abbr kgdepwowideall 'kubectl get deployment --watch -o=wide --all-namespaces'
abbr kgsvcwowideall 'kubectl get service --watch -o=wide --all-namespaces'
abbr kgingwowideall 'kubectl get ingress --watch -o=wide --all-namespaces'
abbr kgcmwowideall 'kubectl get configmap --watch -o=wide --all-namespaces'
abbr kgsecwowideall 'kubectl get secret --watch -o=wide --all-namespaces'
abbr kgnswowideall 'kubectl get namespaces --watch -o=wide --all-namespaces'
abbr kgwallowide 'kubectl get --watch --all-namespaces -o=wide'
abbr kgpowallowide 'kubectl get pods --watch --all-namespaces -o=wide'
abbr kgdepwallowide 'kubectl get deployment --watch --all-namespaces -o=wide'
abbr kgsvcwallowide 'kubectl get service --watch --all-namespaces -o=wide'
abbr kgingwallowide 'kubectl get ingress --watch --all-namespaces -o=wide'
abbr kgcmwallowide 'kubectl get configmap --watch --all-namespaces -o=wide'
abbr kgsecwallowide 'kubectl get secret --watch --all-namespaces -o=wide'
abbr kgnswallowide 'kubectl get namespaces --watch --all-namespaces -o=wide'
abbr kgslwowide 'kubectl get --show-labels --watch -o=wide'
abbr ksysgslwowide 'kubectl --namespace=kube-system get --show-labels --watch -o=wide'
abbr kgposlwowide 'kubectl get pods --show-labels --watch -o=wide'
abbr ksysgposlwowide 'kubectl --namespace=kube-system get pods --show-labels --watch -o=wide'
abbr kgdepslwowide 'kubectl get deployment --show-labels --watch -o=wide'
abbr ksysgdepslwowide 'kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide'
abbr kgwowidesl 'kubectl get --watch -o=wide --show-labels'
abbr ksysgwowidesl 'kubectl --namespace=kube-system get --watch -o=wide --show-labels'
abbr kgpowowidesl 'kubectl get pods --watch -o=wide --show-labels'
abbr ksysgpowowidesl 'kubectl --namespace=kube-system get pods --watch -o=wide --show-labels'
abbr kgdepwowidesl 'kubectl get deployment --watch -o=wide --show-labels'
abbr ksysgdepwowidesl 'kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels'
abbr kgwslowide 'kubectl get --watch --show-labels -o=wide'
abbr ksysgwslowide 'kubectl --namespace=kube-system get --watch --show-labels -o=wide'
abbr kgpowslowide 'kubectl get pods --watch --show-labels -o=wide'
abbr ksysgpowslowide 'kubectl --namespace=kube-system get pods --watch --show-labels -o=wide'
abbr kgdepwslowide 'kubectl get deployment --watch --show-labels -o=wide'
abbr ksysgdepwslowide 'kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide'
abbr kgallwojson 'kubectl get --all-namespaces --watch -o=json'
abbr kgpoallwojson 'kubectl get pods --all-namespaces --watch -o=json'
abbr kgdepallwojson 'kubectl get deployment --all-namespaces --watch -o=json'
abbr kgsvcallwojson 'kubectl get service --all-namespaces --watch -o=json'
abbr kgingallwojson 'kubectl get ingress --all-namespaces --watch -o=json'
abbr kgcmallwojson 'kubectl get configmap --all-namespaces --watch -o=json'
abbr kgsecallwojson 'kubectl get secret --all-namespaces --watch -o=json'
abbr kgnsallwojson 'kubectl get namespaces --all-namespaces --watch -o=json'
abbr kgwojsonall 'kubectl get --watch -o=json --all-namespaces'
abbr kgpowojsonall 'kubectl get pods --watch -o=json --all-namespaces'
abbr kgdepwojsonall 'kubectl get deployment --watch -o=json --all-namespaces'
abbr kgsvcwojsonall 'kubectl get service --watch -o=json --all-namespaces'
abbr kgingwojsonall 'kubectl get ingress --watch -o=json --all-namespaces'
abbr kgcmwojsonall 'kubectl get configmap --watch -o=json --all-namespaces'
abbr kgsecwojsonall 'kubectl get secret --watch -o=json --all-namespaces'
abbr kgnswojsonall 'kubectl get namespaces --watch -o=json --all-namespaces'
abbr kgwallojson 'kubectl get --watch --all-namespaces -o=json'
abbr kgpowallojson 'kubectl get pods --watch --all-namespaces -o=json'
abbr kgdepwallojson 'kubectl get deployment --watch --all-namespaces -o=json'
abbr kgsvcwallojson 'kubectl get service --watch --all-namespaces -o=json'
abbr kgingwallojson 'kubectl get ingress --watch --all-namespaces -o=json'
abbr kgcmwallojson 'kubectl get configmap --watch --all-namespaces -o=json'
abbr kgsecwallojson 'kubectl get secret --watch --all-namespaces -o=json'
abbr kgnswallojson 'kubectl get namespaces --watch --all-namespaces -o=json'
abbr kgallslw 'kubectl get --all-namespaces --show-labels --watch'
abbr kgpoallslw 'kubectl get pods --all-namespaces --show-labels --watch'
abbr kgdepallslw 'kubectl get deployment --all-namespaces --show-labels --watch'
abbr kgallwsl 'kubectl get --all-namespaces --watch --show-labels'
abbr kgpoallwsl 'kubectl get pods --all-namespaces --watch --show-labels'
abbr kgdepallwsl 'kubectl get deployment --all-namespaces --watch --show-labels'
abbr kgslallw 'kubectl get --show-labels --all-namespaces --watch'
abbr kgposlallw 'kubectl get pods --show-labels --all-namespaces --watch'
abbr kgdepslallw 'kubectl get deployment --show-labels --all-namespaces --watch'
abbr kgslwall 'kubectl get --show-labels --watch --all-namespaces'
abbr kgposlwall 'kubectl get pods --show-labels --watch --all-namespaces'
abbr kgdepslwall 'kubectl get deployment --show-labels --watch --all-namespaces'
abbr kgwallsl 'kubectl get --watch --all-namespaces --show-labels'
abbr kgpowallsl 'kubectl get pods --watch --all-namespaces --show-labels'
abbr kgdepwallsl 'kubectl get deployment --watch --all-namespaces --show-labels'
abbr kgwslall 'kubectl get --watch --show-labels --all-namespaces'
abbr kgpowslall 'kubectl get pods --watch --show-labels --all-namespaces'
abbr kgdepwslall 'kubectl get deployment --watch --show-labels --all-namespaces'
abbr kgallslwowide 'kubectl get --all-namespaces --show-labels --watch -o=wide'
abbr kgpoallslwowide 'kubectl get pods --all-namespaces --show-labels --watch -o=wide'
abbr kgdepallslwowide 'kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
abbr kgallwowidesl 'kubectl get --all-namespaces --watch -o=wide --show-labels'
abbr kgpoallwowidesl 'kubectl get pods --all-namespaces --watch -o=wide --show-labels'
abbr kgdepallwowidesl 'kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
abbr kgallwslowide 'kubectl get --all-namespaces --watch --show-labels -o=wide'
abbr kgpoallwslowide 'kubectl get pods --all-namespaces --watch --show-labels -o=wide'
abbr kgdepallwslowide 'kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
abbr kgslallwowide 'kubectl get --show-labels --all-namespaces --watch -o=wide'
abbr kgposlallwowide 'kubectl get pods --show-labels --all-namespaces --watch -o=wide'
abbr kgdepslallwowide 'kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
abbr kgslwowideall 'kubectl get --show-labels --watch -o=wide --all-namespaces'
abbr kgposlwowideall 'kubectl get pods --show-labels --watch -o=wide --all-namespaces'
abbr kgdepslwowideall 'kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
abbr kgslwallowide 'kubectl get --show-labels --watch --all-namespaces -o=wide'
abbr kgposlwallowide 'kubectl get pods --show-labels --watch --all-namespaces -o=wide'
abbr kgdepslwallowide 'kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
abbr kgwowideallsl 'kubectl get --watch -o=wide --all-namespaces --show-labels'
abbr kgpowowideallsl 'kubectl get pods --watch -o=wide --all-namespaces --show-labels'
abbr kgdepwowideallsl 'kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
abbr kgwowideslall 'kubectl get --watch -o=wide --show-labels --all-namespaces'
abbr kgpowowideslall 'kubectl get pods --watch -o=wide --show-labels --all-namespaces'
abbr kgdepwowideslall 'kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
abbr kgwallowidesl 'kubectl get --watch --all-namespaces -o=wide --show-labels'
abbr kgpowallowidesl 'kubectl get pods --watch --all-namespaces -o=wide --show-labels'
abbr kgdepwallowidesl 'kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
abbr kgwallslowide 'kubectl get --watch --all-namespaces --show-labels -o=wide'
abbr kgpowallslowide 'kubectl get pods --watch --all-namespaces --show-labels -o=wide'
abbr kgdepwallslowide 'kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
abbr kgwslowideall 'kubectl get --watch --show-labels -o=wide --all-namespaces'
abbr kgpowslowideall 'kubectl get pods --watch --show-labels -o=wide --all-namespaces'
abbr kgdepwslowideall 'kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
abbr kgwslallowide 'kubectl get --watch --show-labels --all-namespaces -o=wide'
abbr kgpowslallowide 'kubectl get pods --watch --show-labels --all-namespaces -o=wide'
abbr kgdepwslallowide 'kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
abbr kgf 'kubectl get --recursive -f'
abbr kdf 'kubectl describe --recursive -f'
abbr krmf 'kubectl delete --recursive -f'
abbr kgoyamlf 'kubectl get -o=yaml --recursive -f'
abbr kgowidef 'kubectl get -o=wide --recursive -f'
abbr kgojsonf 'kubectl get -o=json --recursive -f'
abbr kgslf 'kubectl get --show-labels --recursive -f'
abbr kgwf 'kubectl get --watch --recursive -f'
abbr kgwoyamlf 'kubectl get --watch -o=yaml --recursive -f'
abbr kgowideslf 'kubectl get -o=wide --show-labels --recursive -f'
abbr kgslowidef 'kubectl get --show-labels -o=wide --recursive -f'
abbr kgwowidef 'kubectl get --watch -o=wide --recursive -f'
abbr kgwojsonf 'kubectl get --watch -o=json --recursive -f'
abbr kgslwf 'kubectl get --show-labels --watch --recursive -f'
abbr kgwslf 'kubectl get --watch --show-labels --recursive -f'
abbr kgslwowidef 'kubectl get --show-labels --watch -o=wide --recursive -f'
abbr kgwowideslf 'kubectl get --watch -o=wide --show-labels --recursive -f'
abbr kgwslowidef 'kubectl get --watch --show-labels -o=wide --recursive -f'
abbr kgl 'kubectl get -l'
abbr ksysgl 'kubectl --namespace=kube-system get -l'
abbr kdl 'kubectl describe -l'
abbr ksysdl 'kubectl --namespace=kube-system describe -l'
abbr krml 'kubectl delete -l'
abbr ksysrml 'kubectl --namespace=kube-system delete -l'
abbr kgpol 'kubectl get pods -l'
abbr ksysgpol 'kubectl --namespace=kube-system get pods -l'
abbr kdpol 'kubectl describe pods -l'
abbr ksysdpol 'kubectl --namespace=kube-system describe pods -l'
abbr krmpol 'kubectl delete pods -l'
abbr ksysrmpol 'kubectl --namespace=kube-system delete pods -l'
abbr kgdepl 'kubectl get deployment -l'
abbr ksysgdepl 'kubectl --namespace=kube-system get deployment -l'
abbr kddepl 'kubectl describe deployment -l'
abbr ksysddepl 'kubectl --namespace=kube-system describe deployment -l'
abbr krmdepl 'kubectl delete deployment -l'
abbr ksysrmdepl 'kubectl --namespace=kube-system delete deployment -l'
abbr kgsvcl 'kubectl get service -l'
abbr ksysgsvcl 'kubectl --namespace=kube-system get service -l'
abbr kdsvcl 'kubectl describe service -l'
abbr ksysdsvcl 'kubectl --namespace=kube-system describe service -l'
abbr krmsvcl 'kubectl delete service -l'
abbr ksysrmsvcl 'kubectl --namespace=kube-system delete service -l'
abbr kgingl 'kubectl get ingress -l'
abbr ksysgingl 'kubectl --namespace=kube-system get ingress -l'
abbr kdingl 'kubectl describe ingress -l'
abbr ksysdingl 'kubectl --namespace=kube-system describe ingress -l'
abbr krmingl 'kubectl delete ingress -l'
abbr ksysrmingl 'kubectl --namespace=kube-system delete ingress -l'
abbr kgcml 'kubectl get configmap -l'
abbr ksysgcml 'kubectl --namespace=kube-system get configmap -l'
abbr kdcml 'kubectl describe configmap -l'
abbr ksysdcml 'kubectl --namespace=kube-system describe configmap -l'
abbr krmcml 'kubectl delete configmap -l'
abbr ksysrmcml 'kubectl --namespace=kube-system delete configmap -l'
abbr kgsecl 'kubectl get secret -l'
abbr ksysgsecl 'kubectl --namespace=kube-system get secret -l'
abbr kdsecl 'kubectl describe secret -l'
abbr ksysdsecl 'kubectl --namespace=kube-system describe secret -l'
abbr krmsecl 'kubectl delete secret -l'
abbr ksysrmsecl 'kubectl --namespace=kube-system delete secret -l'
abbr kgnol 'kubectl get nodes -l'
abbr kdnol 'kubectl describe nodes -l'
abbr kgnsl 'kubectl get namespaces -l'
abbr kdnsl 'kubectl describe namespaces -l'
abbr krmnsl 'kubectl delete namespaces -l'
abbr kgoyamll 'kubectl get -o=yaml -l'
abbr ksysgoyamll 'kubectl --namespace=kube-system get -o=yaml -l'
abbr kgpooyamll 'kubectl get pods -o=yaml -l'
abbr ksysgpooyamll 'kubectl --namespace=kube-system get pods -o=yaml -l'
abbr kgdepoyamll 'kubectl get deployment -o=yaml -l'
abbr ksysgdepoyamll 'kubectl --namespace=kube-system get deployment -o=yaml -l'
abbr kgsvcoyamll 'kubectl get service -o=yaml -l'
abbr ksysgsvcoyamll 'kubectl --namespace=kube-system get service -o=yaml -l'
abbr kgingoyamll 'kubectl get ingress -o=yaml -l'
abbr ksysgingoyamll 'kubectl --namespace=kube-system get ingress -o=yaml -l'
abbr kgcmoyamll 'kubectl get configmap -o=yaml -l'
abbr ksysgcmoyamll 'kubectl --namespace=kube-system get configmap -o=yaml -l'
abbr kgsecoyamll 'kubectl get secret -o=yaml -l'
abbr ksysgsecoyamll 'kubectl --namespace=kube-system get secret -o=yaml -l'
abbr kgnooyamll 'kubectl get nodes -o=yaml -l'
abbr kgnsoyamll 'kubectl get namespaces -o=yaml -l'
abbr kgowidel 'kubectl get -o=wide -l'
abbr ksysgowidel 'kubectl --namespace=kube-system get -o=wide -l'
abbr kgpoowidel 'kubectl get pods -o=wide -l'
abbr ksysgpoowidel 'kubectl --namespace=kube-system get pods -o=wide -l'
abbr kgdepowidel 'kubectl get deployment -o=wide -l'
abbr ksysgdepowidel 'kubectl --namespace=kube-system get deployment -o=wide -l'
abbr kgsvcowidel 'kubectl get service -o=wide -l'
abbr ksysgsvcowidel 'kubectl --namespace=kube-system get service -o=wide -l'
abbr kgingowidel 'kubectl get ingress -o=wide -l'
abbr ksysgingowidel 'kubectl --namespace=kube-system get ingress -o=wide -l'
abbr kgcmowidel 'kubectl get configmap -o=wide -l'
abbr ksysgcmowidel 'kubectl --namespace=kube-system get configmap -o=wide -l'
abbr kgsecowidel 'kubectl get secret -o=wide -l'
abbr ksysgsecowidel 'kubectl --namespace=kube-system get secret -o=wide -l'
abbr kgnoowidel 'kubectl get nodes -o=wide -l'
abbr kgnsowidel 'kubectl get namespaces -o=wide -l'
abbr kgojsonl 'kubectl get -o=json -l'
abbr ksysgojsonl 'kubectl --namespace=kube-system get -o=json -l'
abbr kgpoojsonl 'kubectl get pods -o=json -l'
abbr ksysgpoojsonl 'kubectl --namespace=kube-system get pods -o=json -l'
abbr kgdepojsonl 'kubectl get deployment -o=json -l'
abbr ksysgdepojsonl 'kubectl --namespace=kube-system get deployment -o=json -l'
abbr kgsvcojsonl 'kubectl get service -o=json -l'
abbr ksysgsvcojsonl 'kubectl --namespace=kube-system get service -o=json -l'
abbr kgingojsonl 'kubectl get ingress -o=json -l'
abbr ksysgingojsonl 'kubectl --namespace=kube-system get ingress -o=json -l'
abbr kgcmojsonl 'kubectl get configmap -o=json -l'
abbr ksysgcmojsonl 'kubectl --namespace=kube-system get configmap -o=json -l'
abbr kgsecojsonl 'kubectl get secret -o=json -l'
abbr ksysgsecojsonl 'kubectl --namespace=kube-system get secret -o=json -l'
abbr kgnoojsonl 'kubectl get nodes -o=json -l'
abbr kgnsojsonl 'kubectl get namespaces -o=json -l'
abbr kgsll 'kubectl get --show-labels -l'
abbr ksysgsll 'kubectl --namespace=kube-system get --show-labels -l'
abbr kgposll 'kubectl get pods --show-labels -l'
abbr ksysgposll 'kubectl --namespace=kube-system get pods --show-labels -l'
abbr kgdepsll 'kubectl get deployment --show-labels -l'
abbr ksysgdepsll 'kubectl --namespace=kube-system get deployment --show-labels -l'
abbr kgwl 'kubectl get --watch -l'
abbr ksysgwl 'kubectl --namespace=kube-system get --watch -l'
abbr kgpowl 'kubectl get pods --watch -l'
abbr ksysgpowl 'kubectl --namespace=kube-system get pods --watch -l'
abbr kgdepwl 'kubectl get deployment --watch -l'
abbr ksysgdepwl 'kubectl --namespace=kube-system get deployment --watch -l'
abbr kgsvcwl 'kubectl get service --watch -l'
abbr ksysgsvcwl 'kubectl --namespace=kube-system get service --watch -l'
abbr kgingwl 'kubectl get ingress --watch -l'
abbr ksysgingwl 'kubectl --namespace=kube-system get ingress --watch -l'
abbr kgcmwl 'kubectl get configmap --watch -l'
abbr ksysgcmwl 'kubectl --namespace=kube-system get configmap --watch -l'
abbr kgsecwl 'kubectl get secret --watch -l'
abbr ksysgsecwl 'kubectl --namespace=kube-system get secret --watch -l'
abbr kgnowl 'kubectl get nodes --watch -l'
abbr kgnswl 'kubectl get namespaces --watch -l'
abbr kgwoyamll 'kubectl get --watch -o=yaml -l'
abbr ksysgwoyamll 'kubectl --namespace=kube-system get --watch -o=yaml -l'
abbr kgpowoyamll 'kubectl get pods --watch -o=yaml -l'
abbr ksysgpowoyamll 'kubectl --namespace=kube-system get pods --watch -o=yaml -l'
abbr kgdepwoyamll 'kubectl get deployment --watch -o=yaml -l'
abbr ksysgdepwoyamll 'kubectl --namespace=kube-system get deployment --watch -o=yaml -l'
abbr kgsvcwoyamll 'kubectl get service --watch -o=yaml -l'
abbr ksysgsvcwoyamll 'kubectl --namespace=kube-system get service --watch -o=yaml -l'
abbr kgingwoyamll 'kubectl get ingress --watch -o=yaml -l'
abbr ksysgingwoyamll 'kubectl --namespace=kube-system get ingress --watch -o=yaml -l'
abbr kgcmwoyamll 'kubectl get configmap --watch -o=yaml -l'
abbr ksysgcmwoyamll 'kubectl --namespace=kube-system get configmap --watch -o=yaml -l'
abbr kgsecwoyamll 'kubectl get secret --watch -o=yaml -l'
abbr ksysgsecwoyamll 'kubectl --namespace=kube-system get secret --watch -o=yaml -l'
abbr kgnowoyamll 'kubectl get nodes --watch -o=yaml -l'
abbr kgnswoyamll 'kubectl get namespaces --watch -o=yaml -l'
abbr kgowidesll 'kubectl get -o=wide --show-labels -l'
abbr ksysgowidesll 'kubectl --namespace=kube-system get -o=wide --show-labels -l'
abbr kgpoowidesll 'kubectl get pods -o=wide --show-labels -l'
abbr ksysgpoowidesll 'kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
abbr kgdepowidesll 'kubectl get deployment -o=wide --show-labels -l'
abbr ksysgdepowidesll 'kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
abbr kgslowidel 'kubectl get --show-labels -o=wide -l'
abbr ksysgslowidel 'kubectl --namespace=kube-system get --show-labels -o=wide -l'
abbr kgposlowidel 'kubectl get pods --show-labels -o=wide -l'
abbr ksysgposlowidel 'kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
abbr kgdepslowidel 'kubectl get deployment --show-labels -o=wide -l'
abbr ksysgdepslowidel 'kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
abbr kgwowidel 'kubectl get --watch -o=wide -l'
abbr ksysgwowidel 'kubectl --namespace=kube-system get --watch -o=wide -l'
abbr kgpowowidel 'kubectl get pods --watch -o=wide -l'
abbr ksysgpowowidel 'kubectl --namespace=kube-system get pods --watch -o=wide -l'
abbr kgdepwowidel 'kubectl get deployment --watch -o=wide -l'
abbr ksysgdepwowidel 'kubectl --namespace=kube-system get deployment --watch -o=wide -l'
abbr kgsvcwowidel 'kubectl get service --watch -o=wide -l'
abbr ksysgsvcwowidel 'kubectl --namespace=kube-system get service --watch -o=wide -l'
abbr kgingwowidel 'kubectl get ingress --watch -o=wide -l'
abbr ksysgingwowidel 'kubectl --namespace=kube-system get ingress --watch -o=wide -l'
abbr kgcmwowidel 'kubectl get configmap --watch -o=wide -l'
abbr ksysgcmwowidel 'kubectl --namespace=kube-system get configmap --watch -o=wide -l'
abbr kgsecwowidel 'kubectl get secret --watch -o=wide -l'
abbr ksysgsecwowidel 'kubectl --namespace=kube-system get secret --watch -o=wide -l'
abbr kgnowowidel 'kubectl get nodes --watch -o=wide -l'
abbr kgnswowidel 'kubectl get namespaces --watch -o=wide -l'
abbr kgwojsonl 'kubectl get --watch -o=json -l'
abbr ksysgwojsonl 'kubectl --namespace=kube-system get --watch -o=json -l'
abbr kgpowojsonl 'kubectl get pods --watch -o=json -l'
abbr ksysgpowojsonl 'kubectl --namespace=kube-system get pods --watch -o=json -l'
abbr kgdepwojsonl 'kubectl get deployment --watch -o=json -l'
abbr ksysgdepwojsonl 'kubectl --namespace=kube-system get deployment --watch -o=json -l'
abbr kgsvcwojsonl 'kubectl get service --watch -o=json -l'
abbr ksysgsvcwojsonl 'kubectl --namespace=kube-system get service --watch -o=json -l'
abbr kgingwojsonl 'kubectl get ingress --watch -o=json -l'
abbr ksysgingwojsonl 'kubectl --namespace=kube-system get ingress --watch -o=json -l'
abbr kgcmwojsonl 'kubectl get configmap --watch -o=json -l'
abbr ksysgcmwojsonl 'kubectl --namespace=kube-system get configmap --watch -o=json -l'
abbr kgsecwojsonl 'kubectl get secret --watch -o=json -l'
abbr ksysgsecwojsonl 'kubectl --namespace=kube-system get secret --watch -o=json -l'
abbr kgnowojsonl 'kubectl get nodes --watch -o=json -l'
abbr kgnswojsonl 'kubectl get namespaces --watch -o=json -l'
abbr kgslwl 'kubectl get --show-labels --watch -l'
abbr ksysgslwl 'kubectl --namespace=kube-system get --show-labels --watch -l'
abbr kgposlwl 'kubectl get pods --show-labels --watch -l'
abbr ksysgposlwl 'kubectl --namespace=kube-system get pods --show-labels --watch -l'
abbr kgdepslwl 'kubectl get deployment --show-labels --watch -l'
abbr ksysgdepslwl 'kubectl --namespace=kube-system get deployment --show-labels --watch -l'
abbr kgwsll 'kubectl get --watch --show-labels -l'
abbr ksysgwsll 'kubectl --namespace=kube-system get --watch --show-labels -l'
abbr kgpowsll 'kubectl get pods --watch --show-labels -l'
abbr ksysgpowsll 'kubectl --namespace=kube-system get pods --watch --show-labels -l'
abbr kgdepwsll 'kubectl get deployment --watch --show-labels -l'
abbr ksysgdepwsll 'kubectl --namespace=kube-system get deployment --watch --show-labels -l'
abbr kgslwowidel 'kubectl get --show-labels --watch -o=wide -l'
abbr ksysgslwowidel 'kubectl --namespace=kube-system get --show-labels --watch -o=wide -l'
abbr kgposlwowidel 'kubectl get pods --show-labels --watch -o=wide -l'
abbr ksysgposlwowidel 'kubectl --namespace=kube-system get pods --show-labels --watch -o=wide -l'
abbr kgdepslwowidel 'kubectl get deployment --show-labels --watch -o=wide -l'
abbr ksysgdepslwowidel 'kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
abbr kgwowidesll 'kubectl get --watch -o=wide --show-labels -l'
abbr ksysgwowidesll 'kubectl --namespace=kube-system get --watch -o=wide --show-labels -l'
abbr kgpowowidesll 'kubectl get pods --watch -o=wide --show-labels -l'
abbr ksysgpowowidesll 'kubectl --namespace=kube-system get pods --watch -o=wide --show-labels -l'
abbr kgdepwowidesll 'kubectl get deployment --watch -o=wide --show-labels -l'
abbr ksysgdepwowidesll 'kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
abbr kgwslowidel 'kubectl get --watch --show-labels -o=wide -l'
abbr ksysgwslowidel 'kubectl --namespace=kube-system get --watch --show-labels -o=wide -l'
abbr kgpowslowidel 'kubectl get pods --watch --show-labels -o=wide -l'
abbr ksysgpowslowidel 'kubectl --namespace=kube-system get pods --watch --show-labels -o=wide -l'
abbr kgdepwslowidel 'kubectl get deployment --watch --show-labels -o=wide -l'
abbr ksysgdepwslowidel 'kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
abbr kexn 'kubectl exec -i -t --namespace'
abbr klon 'kubectl logs -f --namespace'
abbr kpfn 'kubectl port-forward --namespace'
abbr kgn 'kubectl get --namespace'
abbr kdn 'kubectl describe --namespace'
abbr krmn 'kubectl delete --namespace'
abbr kgpon 'kubectl get pods --namespace'
abbr kdpon 'kubectl describe pods --namespace'
abbr krmpon 'kubectl delete pods --namespace'
abbr kgdepn 'kubectl get deployment --namespace'
abbr kddepn 'kubectl describe deployment --namespace'
abbr krmdepn 'kubectl delete deployment --namespace'
abbr kgsvcn 'kubectl get service --namespace'
abbr kdsvcn 'kubectl describe service --namespace'
abbr krmsvcn 'kubectl delete service --namespace'
abbr kgingn 'kubectl get ingress --namespace'
abbr kdingn 'kubectl describe ingress --namespace'
abbr krmingn 'kubectl delete ingress --namespace'
abbr kgcmn 'kubectl get configmap --namespace'
abbr kdcmn 'kubectl describe configmap --namespace'
abbr krmcmn 'kubectl delete configmap --namespace'
abbr kgsecn 'kubectl get secret --namespace'
abbr kdsecn 'kubectl describe secret --namespace'
abbr krmsecn 'kubectl delete secret --namespace'
abbr kgoyamln 'kubectl get -o=yaml --namespace'
abbr kgpooyamln 'kubectl get pods -o=yaml --namespace'
abbr kgdepoyamln 'kubectl get deployment -o=yaml --namespace'
abbr kgsvcoyamln 'kubectl get service -o=yaml --namespace'
abbr kgingoyamln 'kubectl get ingress -o=yaml --namespace'
abbr kgcmoyamln 'kubectl get configmap -o=yaml --namespace'
abbr kgsecoyamln 'kubectl get secret -o=yaml --namespace'
abbr kgowiden 'kubectl get -o=wide --namespace'
abbr kgpoowiden 'kubectl get pods -o=wide --namespace'
abbr kgdepowiden 'kubectl get deployment -o=wide --namespace'
abbr kgsvcowiden 'kubectl get service -o=wide --namespace'
abbr kgingowiden 'kubectl get ingress -o=wide --namespace'
abbr kgcmowiden 'kubectl get configmap -o=wide --namespace'
abbr kgsecowiden 'kubectl get secret -o=wide --namespace'
abbr kgojsonn 'kubectl get -o=json --namespace'
abbr kgpoojsonn 'kubectl get pods -o=json --namespace'
abbr kgdepojsonn 'kubectl get deployment -o=json --namespace'
abbr kgsvcojsonn 'kubectl get service -o=json --namespace'
abbr kgingojsonn 'kubectl get ingress -o=json --namespace'
abbr kgcmojsonn 'kubectl get configmap -o=json --namespace'
abbr kgsecojsonn 'kubectl get secret -o=json --namespace'
abbr kgsln 'kubectl get --show-labels --namespace'
abbr kgposln 'kubectl get pods --show-labels --namespace'
abbr kgdepsln 'kubectl get deployment --show-labels --namespace'
abbr kgwn 'kubectl get --watch --namespace'
abbr kgpown 'kubectl get pods --watch --namespace'
abbr kgdepwn 'kubectl get deployment --watch --namespace'
abbr kgsvcwn 'kubectl get service --watch --namespace'
abbr kgingwn 'kubectl get ingress --watch --namespace'
abbr kgcmwn 'kubectl get configmap --watch --namespace'
abbr kgsecwn 'kubectl get secret --watch --namespace'
abbr kgwoyamln 'kubectl get --watch -o=yaml --namespace'
abbr kgpowoyamln 'kubectl get pods --watch -o=yaml --namespace'
abbr kgdepwoyamln 'kubectl get deployment --watch -o=yaml --namespace'
abbr kgsvcwoyamln 'kubectl get service --watch -o=yaml --namespace'
abbr kgingwoyamln 'kubectl get ingress --watch -o=yaml --namespace'
abbr kgcmwoyamln 'kubectl get configmap --watch -o=yaml --namespace'
abbr kgsecwoyamln 'kubectl get secret --watch -o=yaml --namespace'
abbr kgowidesln 'kubectl get -o=wide --show-labels --namespace'
abbr kgpoowidesln 'kubectl get pods -o=wide --show-labels --namespace'
abbr kgdepowidesln 'kubectl get deployment -o=wide --show-labels --namespace'
abbr kgslowiden 'kubectl get --show-labels -o=wide --namespace'
abbr kgposlowiden 'kubectl get pods --show-labels -o=wide --namespace'
abbr kgdepslowiden 'kubectl get deployment --show-labels -o=wide --namespace'
abbr kgwowiden 'kubectl get --watch -o=wide --namespace'
abbr kgpowowiden 'kubectl get pods --watch -o=wide --namespace'
abbr kgdepwowiden 'kubectl get deployment --watch -o=wide --namespace'
abbr kgsvcwowiden 'kubectl get service --watch -o=wide --namespace'
abbr kgingwowiden 'kubectl get ingress --watch -o=wide --namespace'
abbr kgcmwowiden 'kubectl get configmap --watch -o=wide --namespace'
abbr kgsecwowiden 'kubectl get secret --watch -o=wide --namespace'
abbr kgwojsonn 'kubectl get --watch -o=json --namespace'
abbr kgpowojsonn 'kubectl get pods --watch -o=json --namespace'
abbr kgdepwojsonn 'kubectl get deployment --watch -o=json --namespace'
abbr kgsvcwojsonn 'kubectl get service --watch -o=json --namespace'
abbr kgingwojsonn 'kubectl get ingress --watch -o=json --namespace'
abbr kgcmwojsonn 'kubectl get configmap --watch -o=json --namespace'
abbr kgsecwojsonn 'kubectl get secret --watch -o=json --namespace'
abbr kgslwn 'kubectl get --show-labels --watch --namespace'
abbr kgposlwn 'kubectl get pods --show-labels --watch --namespace'
abbr kgdepslwn 'kubectl get deployment --show-labels --watch --namespace'
abbr kgwsln 'kubectl get --watch --show-labels --namespace'
abbr kgpowsln 'kubectl get pods --watch --show-labels --namespace'
abbr kgdepwsln 'kubectl get deployment --watch --show-labels --namespace'
abbr kgslwowiden 'kubectl get --show-labels --watch -o=wide --namespace'
abbr kgposlwowiden 'kubectl get pods --show-labels --watch -o=wide --namespace'
abbr kgdepslwowiden 'kubectl get deployment --show-labels --watch -o=wide --namespace'
abbr kgwowidesln 'kubectl get --watch -o=wide --show-labels --namespace'
abbr kgpowowidesln 'kubectl get pods --watch -o=wide --show-labels --namespace'
abbr kgdepwowidesln 'kubectl get deployment --watch -o=wide --show-labels --namespace'
abbr kgwslowiden 'kubectl get --watch --show-labels -o=wide --namespace'
abbr kgpowslowiden 'kubectl get pods --watch --show-labels -o=wide --namespace'
abbr kgdepwslowiden 'kubectl get deployment --watch --show-labels -o=wide --namespace'

## K8S autocompletion
# source ~/.helmrc
# source <(kubectl completion zsh)

kubectl completion fish | source

## Poetry
export PATH="$HOME/.poetry/bin:$PATH"
#poetry completions zsh > ~/.zfunc/_poetry

#autoload -U +X bashcompinit && bashcompinit
#complete -o nospace -C /usr/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/apinter/Downloads/google-cloud-sdk/path.fish.inc' ]; . '/home/apinter/Downloads/google-cloud-sdk/path.fish.inc'; end

end
## Linode

# This is a generated file by Linode-CLI! Do not modify!
complete -c linode-cli -n "not __fish_seen_subcommand_from account events payment-methods service-transfers users databases domains images linodes kernels stackscripts lke longview managed networking firewalls vlans nodebalancers object-storage profile security-questions sshkeys phone regions tickets tags volumes" -x -a 'account events payment-methods service-transfers users databases domains images linodes kernels stackscripts lke longview managed networking firewalls vlans nodebalancers object-storage profile security-questions sshkeys phone regions tickets tags volumes --help'
complete -c linode -n "not __fish_seen_subcommand_from account events payment-methods service-transfers users databases domains images linodes kernels stackscripts lke longview managed networking firewalls vlans nodebalancers object-storage profile security-questions sshkeys phone regions tickets tags volumes" -x -a 'account events payment-methods service-transfers users databases domains images linodes kernels stackscripts lke longview managed networking firewalls vlans nodebalancers object-storage profile security-questions sshkeys phone regions tickets tags volumes --help'
complete -c lin -n "not __fish_seen_subcommand_from account events payment-methods service-transfers users databases domains images linodes kernels stackscripts lke longview managed networking firewalls vlans nodebalancers object-storage profile security-questions sshkeys phone regions tickets tags volumes" -x -a 'account events payment-methods service-transfers users databases domains images linodes kernels stackscripts lke longview managed networking firewalls vlans nodebalancers object-storage profile security-questions sshkeys phone regions tickets tags volumes --help'
complete -c linode-cli -n "__fish_seen_subcommand_from account" -x -a 'view update cancel invoices-list invoice-view invoice-items logins-list login-view maintenance-list notifications-list clients-list client-create client-view client-update client-delete client-reset-secret payments-list payment-create payment-view promo-add settings settings-update enable-managed transfer --help'
complete -c linode -n "__fish_seen_subcommand_from account" -x -a 'view update cancel invoices-list invoice-view invoice-items logins-list login-view maintenance-list notifications-list clients-list client-create client-view client-update client-delete client-reset-secret payments-list payment-create payment-view promo-add settings settings-update enable-managed transfer --help'
complete -c lin -n "__fish_seen_subcommand_from account" -x -a 'view update cancel invoices-list invoice-view invoice-items logins-list login-view maintenance-list notifications-list clients-list client-create client-view client-update client-delete client-reset-secret payments-list payment-create payment-view promo-add settings settings-update enable-managed transfer --help'
complete -c linode-cli -n "__fish_seen_subcommand_from events" -x -a 'list view mark-read mark-seen --help'
complete -c linode -n "__fish_seen_subcommand_from events" -x -a 'list view mark-read mark-seen --help'
complete -c lin -n "__fish_seen_subcommand_from events" -x -a 'list view mark-read mark-seen --help'
complete -c linode-cli -n "__fish_seen_subcommand_from payment-methods" -x -a 'list add view delete default --help'
complete -c linode -n "__fish_seen_subcommand_from payment-methods" -x -a 'list add view delete default --help'
complete -c lin -n "__fish_seen_subcommand_from payment-methods" -x -a 'list add view delete default --help'
complete -c linode-cli -n "__fish_seen_subcommand_from service-transfers" -x -a 'list create view cancel accept --help'
complete -c linode -n "__fish_seen_subcommand_from service-transfers" -x -a 'list create view cancel accept --help'
complete -c lin -n "__fish_seen_subcommand_from service-transfers" -x -a 'list create view cancel accept --help'
complete -c linode-cli -n "__fish_seen_subcommand_from users" -x -a 'list create view update delete --help'
complete -c linode -n "__fish_seen_subcommand_from users" -x -a 'list create view update delete --help'
complete -c lin -n "__fish_seen_subcommand_from users" -x -a 'list create view update delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from databases" -x -a 'engines engine-view list mysql-list mysql-create mysql-view mysql-update mysql-delete mysql-backups-list mysql-backup-snapshot mysql-backup-view mysql-backup-delete mysql-backup-restore mysql-creds-view mysql-creds-reset mysql-ssl-cert mysql-patch postgresql-list postgresql-create postgresql-view postgresql-update postgresql-delete postgresql-backups-list postgresql-backup-snapshot postgresql-backup-view postgresql-backup-delete postgresql-backup-restore postgresql-creds-view postgresql-creds-reset postgresql-ssl-cert postgresql-patch types type-view --help'
complete -c linode -n "__fish_seen_subcommand_from databases" -x -a 'engines engine-view list mysql-list mysql-create mysql-view mysql-update mysql-delete mysql-backups-list mysql-backup-snapshot mysql-backup-view mysql-backup-delete mysql-backup-restore mysql-creds-view mysql-creds-reset mysql-ssl-cert mysql-patch postgresql-list postgresql-create postgresql-view postgresql-update postgresql-delete postgresql-backups-list postgresql-backup-snapshot postgresql-backup-view postgresql-backup-delete postgresql-backup-restore postgresql-creds-view postgresql-creds-reset postgresql-ssl-cert postgresql-patch types type-view --help'
complete -c lin -n "__fish_seen_subcommand_from databases" -x -a 'engines engine-view list mysql-list mysql-create mysql-view mysql-update mysql-delete mysql-backups-list mysql-backup-snapshot mysql-backup-view mysql-backup-delete mysql-backup-restore mysql-creds-view mysql-creds-reset mysql-ssl-cert mysql-patch postgresql-list postgresql-create postgresql-view postgresql-update postgresql-delete postgresql-backups-list postgresql-backup-snapshot postgresql-backup-view postgresql-backup-delete postgresql-backup-restore postgresql-creds-view postgresql-creds-reset postgresql-ssl-cert postgresql-patch types type-view --help'
complete -c linode-cli -n "__fish_seen_subcommand_from domains" -x -a 'list create view update delete zone-file import clone records-list records-create records-view records-update records-delete --help'
complete -c linode -n "__fish_seen_subcommand_from domains" -x -a 'list create view update delete zone-file import clone records-list records-create records-view records-update records-delete --help'
complete -c lin -n "__fish_seen_subcommand_from domains" -x -a 'list create view update delete zone-file import clone records-list records-create records-view records-update records-delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from images" -x -a 'list create upload view update delete --help'
complete -c linode -n "__fish_seen_subcommand_from images" -x -a 'list create upload view update delete --help'
complete -c lin -n "__fish_seen_subcommand_from images" -x -a 'list create upload view update delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from linodes" -x -a 'list create view update delete backups-list snapshot backups-cancel backups-enable backup-view backup-restore boot clone configs-list config-create config-view config-update config-delete disks-list disk-create disk-view disk-update disk-delete disk-clone disk-reset-password disk-resize firewalls-list ips-list ip-add ip-view ip-update ip-delete migrate upgrade nodebalancers linode-reset-password reboot rebuild rescue resize shutdown transfer-view volumes types type-view --help'
complete -c linode -n "__fish_seen_subcommand_from linodes" -x -a 'list create view update delete backups-list snapshot backups-cancel backups-enable backup-view backup-restore boot clone configs-list config-create config-view config-update config-delete disks-list disk-create disk-view disk-update disk-delete disk-clone disk-reset-password disk-resize firewalls-list ips-list ip-add ip-view ip-update ip-delete migrate upgrade nodebalancers linode-reset-password reboot rebuild rescue resize shutdown transfer-view volumes types type-view --help'
complete -c lin -n "__fish_seen_subcommand_from linodes" -x -a 'list create view update delete backups-list snapshot backups-cancel backups-enable backup-view backup-restore boot clone configs-list config-create config-view config-update config-delete disks-list disk-create disk-view disk-update disk-delete disk-clone disk-reset-password disk-resize firewalls-list ips-list ip-add ip-view ip-update ip-delete migrate upgrade nodebalancers linode-reset-password reboot rebuild rescue resize shutdown transfer-view volumes types type-view --help'
complete -c linode-cli -n "__fish_seen_subcommand_from kernels" -x -a 'list view --help'
complete -c linode -n "__fish_seen_subcommand_from kernels" -x -a 'list view --help'
complete -c lin -n "__fish_seen_subcommand_from kernels" -x -a 'list view --help'
complete -c linode-cli -n "__fish_seen_subcommand_from stackscripts" -x -a 'list create view update delete --help'
complete -c linode -n "__fish_seen_subcommand_from stackscripts" -x -a 'list create view update delete --help'
complete -c lin -n "__fish_seen_subcommand_from stackscripts" -x -a 'list create view update delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from lke" -x -a 'clusters-list cluster-create cluster-view cluster-update cluster-delete pools-list pool-create cluster-nodes-recycle pool-view pool-update pool-delete pool-recycle node-view node-delete node-recycle api-endpoints-list cluster-dashboard-url kubeconfig-view kubeconfig-delete regenerate service-token-delete versions-list version-view --help'
complete -c linode -n "__fish_seen_subcommand_from lke" -x -a 'clusters-list cluster-create cluster-view cluster-update cluster-delete pools-list pool-create cluster-nodes-recycle pool-view pool-update pool-delete pool-recycle node-view node-delete node-recycle api-endpoints-list cluster-dashboard-url kubeconfig-view kubeconfig-delete regenerate service-token-delete versions-list version-view --help'
complete -c lin -n "__fish_seen_subcommand_from lke" -x -a 'clusters-list cluster-create cluster-view cluster-update cluster-delete pools-list pool-create cluster-nodes-recycle pool-view pool-update pool-delete pool-recycle node-view node-delete node-recycle api-endpoints-list cluster-dashboard-url kubeconfig-view kubeconfig-delete regenerate service-token-delete versions-list version-view --help'
complete -c linode-cli -n "__fish_seen_subcommand_from longview" -x -a 'list create view update delete plan-view plan-update subscriptions-list subscription-view --help'
complete -c linode -n "__fish_seen_subcommand_from longview" -x -a 'list create view update delete plan-view plan-update subscriptions-list subscription-view --help'
complete -c lin -n "__fish_seen_subcommand_from longview" -x -a 'list create view update delete plan-view plan-update subscriptions-list subscription-view --help'
complete -c linode-cli -n "__fish_seen_subcommand_from managed" -x -a 'contacts-list contact-create contact-view contact-update contact-delete credentials-list credential-create credential-view credential-update credential-update-username-password credential-revoke credential-sshkey-view issues-list issue-view linode-settings-list linode-setting-view linode-setting-update services-list service-create service-view service-update service-delete service-disable service-enable stats-list --help'
complete -c linode -n "__fish_seen_subcommand_from managed" -x -a 'contacts-list contact-create contact-view contact-update contact-delete credentials-list credential-create credential-view credential-update credential-update-username-password credential-revoke credential-sshkey-view issues-list issue-view linode-settings-list linode-setting-view linode-setting-update services-list service-create service-view service-update service-delete service-disable service-enable stats-list --help'
complete -c lin -n "__fish_seen_subcommand_from managed" -x -a 'contacts-list contact-create contact-view contact-update contact-delete credentials-list credential-create credential-view credential-update credential-update-username-password credential-revoke credential-sshkey-view issues-list issue-view linode-settings-list linode-setting-view linode-setting-update services-list service-create service-view service-update service-delete service-disable service-enable stats-list --help'
complete -c linode-cli -n "__fish_seen_subcommand_from networking" -x -a 'ips-list ip-add ip-view ip-update ip-assign ip-share v6-pools v6-ranges v6-range-create v6-range-view v6-range-delete --help'
complete -c linode -n "__fish_seen_subcommand_from networking" -x -a 'ips-list ip-add ip-view ip-update ip-assign ip-share v6-pools v6-ranges v6-range-create v6-range-view v6-range-delete --help'
complete -c lin -n "__fish_seen_subcommand_from networking" -x -a 'ips-list ip-add ip-view ip-update ip-assign ip-share v6-pools v6-ranges v6-range-create v6-range-view v6-range-delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from firewalls" -x -a 'list create view update delete devices-list device-create device-view device-delete rules-list rules-update --help'
complete -c linode -n "__fish_seen_subcommand_from firewalls" -x -a 'list create view update delete devices-list device-create device-view device-delete rules-list rules-update --help'
complete -c lin -n "__fish_seen_subcommand_from firewalls" -x -a 'list create view update delete devices-list device-create device-view device-delete rules-list rules-update --help'
complete -c linode-cli -n "__fish_seen_subcommand_from vlans" -x -a 'list --help'
complete -c linode -n "__fish_seen_subcommand_from vlans" -x -a 'list --help'
complete -c lin -n "__fish_seen_subcommand_from vlans" -x -a 'list --help'
complete -c linode-cli -n "__fish_seen_subcommand_from nodebalancers" -x -a 'list create view update delete configs-list config-create config-view config-update config-delete config-rebuild nodes-list node-create node-view node-update node-delete --help'
complete -c linode -n "__fish_seen_subcommand_from nodebalancers" -x -a 'list create view update delete configs-list config-create config-view config-update config-delete config-rebuild nodes-list node-create node-view node-update node-delete --help'
complete -c lin -n "__fish_seen_subcommand_from nodebalancers" -x -a 'list create view update delete configs-list config-create config-view config-update config-delete config-rebuild nodes-list node-create node-view node-update node-delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from object-storage" -x -a 'clusters-list clusters-view keys-list keys-create keys-view keys-update keys-delete cancel ssl-view ssl-upload ssl-delete --help'
complete -c linode -n "__fish_seen_subcommand_from object-storage" -x -a 'clusters-list clusters-view keys-list keys-create keys-view keys-update keys-delete cancel ssl-view ssl-upload ssl-delete --help'
complete -c lin -n "__fish_seen_subcommand_from object-storage" -x -a 'clusters-list clusters-view keys-list keys-create keys-view keys-update keys-delete cancel ssl-view ssl-upload ssl-delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from profile" -x -a 'view update apps-list app-view app-delete tfa-disable tfa-enable tfa-confirm tokens-list token-create token-view token-update token-delete logins-list login-view devices-list device-view device-revoke --help'
complete -c linode -n "__fish_seen_subcommand_from profile" -x -a 'view update apps-list app-view app-delete tfa-disable tfa-enable tfa-confirm tokens-list token-create token-view token-update token-delete logins-list login-view devices-list device-view device-revoke --help'
complete -c lin -n "__fish_seen_subcommand_from profile" -x -a 'view update apps-list app-view app-delete tfa-disable tfa-enable tfa-confirm tokens-list token-create token-view token-update token-delete logins-list login-view devices-list device-view device-revoke --help'
complete -c linode-cli -n "__fish_seen_subcommand_from security-questions" -x -a 'list --help'
complete -c linode -n "__fish_seen_subcommand_from security-questions" -x -a 'list --help'
complete -c lin -n "__fish_seen_subcommand_from security-questions" -x -a 'list --help'
complete -c linode-cli -n "__fish_seen_subcommand_from sshkeys" -x -a 'list create view update delete --help'
complete -c linode -n "__fish_seen_subcommand_from sshkeys" -x -a 'list create view update delete --help'
complete -c lin -n "__fish_seen_subcommand_from sshkeys" -x -a 'list create view update delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from phone" -x -a 'sms-code-send delete verify --help'
complete -c linode -n "__fish_seen_subcommand_from phone" -x -a 'sms-code-send delete verify --help'
complete -c lin -n "__fish_seen_subcommand_from phone" -x -a 'sms-code-send delete verify --help'
complete -c linode-cli -n "__fish_seen_subcommand_from regions" -x -a 'list view --help'
complete -c linode -n "__fish_seen_subcommand_from regions" -x -a 'list view --help'
complete -c lin -n "__fish_seen_subcommand_from regions" -x -a 'list view --help'
complete -c linode-cli -n "__fish_seen_subcommand_from tickets" -x -a 'list create view close replies reply --help'
complete -c linode -n "__fish_seen_subcommand_from tickets" -x -a 'list create view close replies reply --help'
complete -c lin -n "__fish_seen_subcommand_from tickets" -x -a 'list create view close replies reply --help'
complete -c linode-cli -n "__fish_seen_subcommand_from tags" -x -a 'list create delete --help'
complete -c linode -n "__fish_seen_subcommand_from tags" -x -a 'list create delete --help'
complete -c lin -n "__fish_seen_subcommand_from tags" -x -a 'list create delete --help'
complete -c linode-cli -n "__fish_seen_subcommand_from volumes" -x -a 'list create view update delete attach clone detach resize --help'
complete -c linode -n "__fish_seen_subcommand_from volumes" -x -a 'list create view update delete attach clone detach resize --help'
complete -c lin -n "__fish_seen_subcommand_from volumes" -x -a 'list create view update delete attach clone detach resize --help'

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
set --export --prepend PATH "/home/apinter/.rd/bin"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

zoxide init --cmd cd fish | source

